import { 
  User, 
  Lead, 
  Company, 
  Contact, 
  Deal, 
  Quotation, 
  Task, 
  Activity,
  WorkspaceSettings 
} from '../types/crm';

export const INITIAL_USER: User = {
  id: 'usr_01',
  name: 'Alex Rivera',
  email: 'alex.rivera@zancrm.internal',
  role: 'sales_manager',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
  title: 'VP of Sales & Revenue Operations',
  phone: '+1 (555) 349-2801',
  timezone: 'America/New_York (EST)',
  notificationsEnabled: true,
};

export const INITIAL_COMPANIES: Company[] = [
  {
    id: 'comp_01',
    name: 'Vertex AI Systems',
    domain: 'vertexai.io',
    industry: 'Enterprise Software / AI',
    size: '250-500',
    phone: '+1 (415) 890-1200',
    city: 'San Francisco, CA',
    country: 'United States',
    totalRevenue: 240000,
    openDealsCount: 2,
    createdAt: '2026-01-10T09:00:00Z',
  },
  {
    id: 'comp_02',
    name: 'Apex Global Logistics',
    domain: 'apexlogistics.com',
    industry: 'Supply Chain & Freight',
    size: '1,000-5,000',
    phone: '+1 (312) 450-8910',
    city: 'Chicago, IL',
    country: 'United States',
    totalRevenue: 185000,
    openDealsCount: 1,
    createdAt: '2026-01-15T11:30:00Z',
  },
  {
    id: 'comp_03',
    name: 'BioGenix Life Sciences',
    domain: 'biogenix.health',
    industry: 'Healthcare & Biotech',
    size: '50-200',
    phone: '+1 (617) 220-4491',
    city: 'Boston, MA',
    country: 'United States',
    totalRevenue: 95000,
    openDealsCount: 1,
    createdAt: '2026-02-01T14:20:00Z',
  },
  {
    id: 'comp_04',
    name: 'FinStream Payments',
    domain: 'finstream.tech',
    industry: 'Fintech & Banking',
    size: '500-1,000',
    phone: '+44 20 7946 0912',
    city: 'London',
    country: 'United Kingdom',
    totalRevenue: 320000,
    openDealsCount: 1,
    createdAt: '2026-02-14T10:15:00Z',
  },
  {
    id: 'comp_05',
    name: 'CyberShield Security',
    domain: 'cybershield.cloud',
    industry: 'Cybersecurity',
    size: '100-250',
    phone: '+1 (512) 330-9988',
    city: 'Austin, TX',
    country: 'United States',
    totalRevenue: 140000,
    openDealsCount: 1,
    createdAt: '2026-03-01T16:45:00Z',
  },
];

export const INITIAL_CONTACTS: Contact[] = [
  {
    id: 'cont_01',
    name: 'Sarah Chen',
    email: 'sarah.chen@vertexai.io',
    phone: '+1 (415) 890-1201',
    title: 'Chief Technology Officer',
    companyId: 'comp_01',
    companyName: 'Vertex AI Systems',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=256&q=80',
    lifecycleStage: 'customer',
    lastActivityAt: '2026-09-24T14:30:00Z',
    assignedTo: 'usr_01',
    notes: 'Key decision maker for enterprise LLM infrastructure upgrade.',
    createdAt: '2026-01-12T10:00:00Z',
  },
  {
    id: 'cont_02',
    name: 'Marcus Vance',
    email: 'm.vance@apexlogistics.com',
    phone: '+1 (312) 450-8914',
    title: 'VP of Global Operations',
    companyId: 'comp_02',
    companyName: 'Apex Global Logistics',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    lifecycleStage: 'mql',
    lastActivityAt: '2026-09-25T11:15:00Z',
    assignedTo: 'usr_01',
    notes: 'Looking to replace legacy tracking software across 14 freight hubs.',
    createdAt: '2026-01-18T13:45:00Z',
  },
  {
    id: 'cont_03',
    name: 'Dr. Elena Rostova',
    email: 'elena.r@biogenix.health',
    phone: '+1 (617) 220-4495',
    title: 'Head of Clinical Research',
    companyId: 'comp_03',
    companyName: 'BioGenix Life Sciences',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=256&q=80',
    lifecycleStage: 'lead',
    lastActivityAt: '2026-09-22T09:00:00Z',
    assignedTo: 'usr_01',
    notes: 'Met at BioMed Expo. Interested in compliance automation suite.',
    createdAt: '2026-02-05T15:30:00Z',
  },
  {
    id: 'cont_04',
    name: 'Julian Thorne',
    email: 'j.thorne@finstream.tech',
    phone: '+44 20 7946 0915',
    title: 'Managing Director of Fintech Ops',
    companyId: 'comp_04',
    companyName: 'FinStream Payments',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
    lifecycleStage: 'customer',
    lastActivityAt: '2026-09-23T16:20:00Z',
    assignedTo: 'usr_01',
    notes: 'Finalizing annual contract renewal and expanding seat count.',
    createdAt: '2026-02-15T11:00:00Z',
  },
  {
    id: 'cont_05',
    name: 'Priya Sharma',
    email: 'priya.s@cybershield.cloud',
    phone: '+1 (512) 330-9990',
    title: 'Chief Information Security Officer',
    companyId: 'comp_05',
    companyName: 'CyberShield Security',
    avatar: 'https://images.unsplash.com/photo-1534751516642-a171ef282497?auto=format&fit=crop&w=256&q=80',
    lifecycleStage: 'customer',
    lastActivityAt: '2026-09-25T17:40:00Z',
    assignedTo: 'usr_01',
    notes: 'Fast-moving security audit engagement.',
    createdAt: '2026-03-02T10:30:00Z',
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead_01',
    name: 'David Sterling',
    company: 'HyperScale Cloud Labs',
    email: 'd.sterling@hyperscale.dev',
    phone: '+1 (206) 555-0144',
    source: 'inbound_call',
    status: 'qualified',
    score: 92,
    assignedTo: 'usr_01',
    estimatedValue: 75000,
    notes: 'Urgent requirement for multi-cloud migration monitoring.',
    createdAt: '2026-09-20T10:15:00Z',
    updatedAt: '2026-09-25T08:00:00Z',
  },
  {
    id: 'lead_02',
    name: 'Nadia Kowalski',
    company: 'Nordic Retail Group',
    email: 'n.kowalski@nordicretail.se',
    phone: '+46 8 123 4567',
    source: 'website',
    status: 'contacted',
    score: 78,
    assignedTo: 'usr_01',
    estimatedValue: 48000,
    notes: 'Downloaded whitepaper on Omnichannel Revenue Optimization.',
    createdAt: '2026-09-21T14:40:00Z',
    updatedAt: '2026-09-24T12:00:00Z',
  },
  {
    id: 'lead_03',
    name: 'Carlos Mendoza',
    company: 'Terra Solar Energy',
    email: 'carlos@terrasolar.es',
    phone: '+34 91 555 4321',
    source: 'referral',
    status: 'new',
    score: 85,
    assignedTo: 'usr_01',
    estimatedValue: 62000,
    notes: 'Referred by Julian Thorne. Exploring enterprise licensing.',
    createdAt: '2026-09-25T09:30:00Z',
    updatedAt: '2026-09-25T09:30:00Z',
  },
  {
    id: 'lead_04',
    name: 'Amara Okafor',
    company: 'Zenith Logistics Hub',
    email: 'amara.o@zenithlog.com',
    phone: '+234 1 234 5678',
    source: 'linkedin',
    status: 'contacted',
    score: 65,
    assignedTo: 'usr_01',
    estimatedValue: 35000,
    notes: 'Sent introductory message and demo video link.',
    createdAt: '2026-09-18T16:00:00Z',
    updatedAt: '2026-09-23T11:20:00Z',
  },
  {
    id: 'lead_05',
    name: 'Liam O’Connor',
    company: 'Emerald Wealth Partners',
    email: 'liam@emeraldwealth.ie',
    phone: '+353 1 496 0000',
    source: 'event',
    status: 'unqualified',
    score: 40,
    assignedTo: 'usr_01',
    estimatedValue: 12000,
    notes: 'Budget constraints for Q3, revisit next fiscal year.',
    createdAt: '2026-09-15T08:30:00Z',
    updatedAt: '2026-09-19T14:10:00Z',
  },
];

export const INITIAL_DEALS: Deal[] = [
  {
    id: 'deal_01',
    title: 'Enterprise AI Suite Expansion',
    value: 120000,
    currency: 'USD',
    stage: 'negotiation',
    probability: 80,
    expectedCloseDate: '2026-10-15',
    companyId: 'comp_01',
    companyName: 'Vertex AI Systems',
    contactId: 'cont_01',
    contactName: 'Sarah Chen',
    assignedTo: 'usr_01',
    priority: 'high',
    tags: ['AI Engine', 'Enterprise', 'Multi-Year'],
    createdAt: '2026-08-10T11:00:00Z',
    updatedAt: '2026-09-24T15:00:00Z',
  },
  {
    id: 'deal_02',
    title: 'Global Fleet Automation Contract',
    value: 85000,
    currency: 'USD',
    stage: 'proposal_sent',
    probability: 60,
    expectedCloseDate: '2026-10-30',
    companyId: 'comp_02',
    companyName: 'Apex Global Logistics',
    contactId: 'cont_02',
    contactName: 'Marcus Vance',
    assignedTo: 'usr_01',
    priority: 'high',
    tags: ['Logistics', 'Hardware Sync'],
    createdAt: '2026-08-22T09:30:00Z',
    updatedAt: '2026-09-25T11:45:00Z',
  },
  {
    id: 'deal_03',
    title: 'Clinical Data Compliance Module',
    value: 64000,
    currency: 'USD',
    stage: 'needs_analysis',
    probability: 45,
    expectedCloseDate: '2026-11-10',
    companyId: 'comp_03',
    companyName: 'BioGenix Life Sciences',
    contactId: 'cont_03',
    contactName: 'Dr. Elena Rostova',
    assignedTo: 'usr_01',
    priority: 'medium',
    tags: ['Healthcare', 'HIPAA'],
    createdAt: '2026-09-01T14:15:00Z',
    updatedAt: '2026-09-22T10:00:00Z',
  },
  {
    id: 'deal_04',
    title: 'Cross-Border Clearing Gateway',
    value: 150000,
    currency: 'USD',
    stage: 'closed_won',
    probability: 100,
    expectedCloseDate: '2026-09-18',
    companyId: 'comp_04',
    companyName: 'FinStream Payments',
    contactId: 'cont_04',
    contactName: 'Julian Thorne',
    assignedTo: 'usr_01',
    priority: 'high',
    tags: ['Fintech', 'Tier-1'],
    createdAt: '2026-07-15T10:00:00Z',
    updatedAt: '2026-09-18T18:00:00Z',
  },
  {
    id: 'deal_05',
    title: 'Cloud Security Mesh License',
    value: 55000,
    currency: 'USD',
    stage: 'qualification',
    probability: 25,
    expectedCloseDate: '2026-11-25',
    companyId: 'comp_05',
    companyName: 'CyberShield Security',
    contactId: 'cont_05',
    contactName: 'Priya Sharma',
    assignedTo: 'usr_01',
    priority: 'low',
    tags: ['Security', 'Trial'],
    createdAt: '2026-09-12T16:00:00Z',
    updatedAt: '2026-09-25T16:30:00Z',
  },
  {
    id: 'deal_06',
    title: 'Omnichannel CRM Integration',
    value: 42000,
    currency: 'USD',
    stage: 'closed_lost',
    probability: 0,
    expectedCloseDate: '2026-09-10',
    companyName: 'Legacy Retailers Inc',
    contactName: 'Tom Bradley',
    assignedTo: 'usr_01',
    priority: 'low',
    tags: ['Lost to Competitor'],
    createdAt: '2026-07-20T10:00:00Z',
    updatedAt: '2026-09-10T14:00:00Z',
  },
];

export const INITIAL_QUOTATIONS: Quotation[] = [
  {
    id: 'quot_01',
    quoteNumber: 'Q-2026-089',
    title: 'Enterprise AI Suite Expansion Quote',
    dealId: 'deal_01',
    dealTitle: 'Enterprise AI Suite Expansion',
    contactName: 'Sarah Chen',
    contactEmail: 'sarah.chen@vertexai.io',
    companyName: 'Vertex AI Systems',
    status: 'sent',
    issueDate: '2026-09-20',
    validUntil: '2026-10-20',
    subtotal: 110000,
    taxRate: 10,
    taxAmount: 11000,
    total: 121000,
    notes: 'Includes dedicated account manager and 24/7 SLA.',
    terms: 'Net 30 payment terms upon contract countersignature.',
    createdBy: 'Alex Rivera',
    createdAt: '2026-09-20T12:00:00Z',
    lineItems: [
      {
        id: 'li_01',
        description: 'ZanCRM Enterprise Cluster (100 seats, Annual)',
        quantity: 1,
        unitPrice: 85000,
        discount: 0,
        amount: 85000,
      },
      {
        id: 'li_02',
        description: 'Advanced AI Pipeline & Predictive Lead Scoring Add-on',
        quantity: 1,
        unitPrice: 25000,
        discount: 0,
        amount: 25000,
      },
    ],
  },
  {
    id: 'quot_02',
    quoteNumber: 'Q-2026-088',
    title: 'Global Fleet Automation Solution Quote',
    dealId: 'deal_02',
    dealTitle: 'Global Fleet Automation Contract',
    contactName: 'Marcus Vance',
    contactEmail: 'm.vance@apexlogistics.com',
    companyName: 'Apex Global Logistics',
    status: 'sent',
    issueDate: '2026-09-24',
    validUntil: '2026-10-24',
    subtotal: 85000,
    taxRate: 0,
    taxAmount: 0,
    total: 85000,
    notes: 'Special freight carrier bundle pricing applied.',
    terms: '50% deposit upfront, 50% upon deployment sign-off.',
    createdBy: 'Alex Rivera',
    createdAt: '2026-09-24T15:20:00Z',
    lineItems: [
      {
        id: 'li_03',
        description: 'Fleet Dispatch Sync Connector & API Webhooks',
        quantity: 1,
        unitPrice: 55000,
        discount: 0,
        amount: 55000,
      },
      {
        id: 'li_04',
        description: 'Custom ERP Data Warehouse Integration & Migration',
        quantity: 1,
        unitPrice: 30000,
        discount: 0,
        amount: 30000,
      },
    ],
  },
  {
    id: 'quot_03',
    quoteNumber: 'Q-2026-085',
    title: 'Cross-Border Clearing Gateway Agreement',
    dealId: 'deal_04',
    dealTitle: 'Cross-Border Clearing Gateway',
    contactName: 'Julian Thorne',
    contactEmail: 'j.thorne@finstream.tech',
    companyName: 'FinStream Payments',
    status: 'accepted',
    issueDate: '2026-09-12',
    validUntil: '2026-09-30',
    subtotal: 150000,
    taxRate: 0,
    taxAmount: 0,
    total: 150000,
    notes: 'Signed and executed on 2026-09-18.',
    terms: 'Billed annually in advance.',
    createdBy: 'Alex Rivera',
    createdAt: '2026-09-12T10:00:00Z',
    lineItems: [
      {
        id: 'li_05',
        description: 'ZanCRM Unlimited Tier + Dedicated Private VPC Hosting',
        quantity: 1,
        unitPrice: 150000,
        discount: 0,
        amount: 150000,
      },
    ],
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task_01',
    title: 'Follow-up Call with Sarah Chen on SLA terms',
    description: 'Review custom security appendix and enterprise data retention policies.',
    type: 'call',
    priority: 'urgent',
    status: 'pending',
    dueDate: '2026-09-26', // Today
    dueTime: '11:00 AM',
    assignedTo: 'usr_01',
    relatedToType: 'deal',
    relatedToId: 'deal_01',
    relatedToName: 'Enterprise AI Suite Expansion',
    isRecurring: false,
    createdAt: '2026-09-25T14:00:00Z',
  },
  {
    id: 'task_02',
    title: 'Send revised Quotation Q-2026-088 to Marcus Vance',
    description: 'Include the 5% multi-site dispatch discount agreed on Wednesday.',
    type: 'email',
    priority: 'high',
    status: 'pending',
    dueDate: '2026-09-26', // Today
    dueTime: '02:30 PM',
    assignedTo: 'usr_01',
    relatedToType: 'deal',
    relatedToId: 'deal_02',
    relatedToName: 'Global Fleet Automation Contract',
    createdAt: '2026-09-25T16:00:00Z',
  },
  {
    id: 'task_03',
    title: 'Discovery & Needs Assessment with Dr. Elena Rostova',
    description: 'Walk through clinical trial tracking workflows and HIPAA compliance checklist.',
    type: 'meeting',
    priority: 'medium',
    status: 'pending',
    dueDate: '2026-09-27',
    dueTime: '10:00 AM',
    assignedTo: 'usr_01',
    relatedToType: 'deal',
    relatedToId: 'deal_03',
    relatedToName: 'Clinical Data Compliance Module',
    createdAt: '2026-09-24T11:00:00Z',
  },
  {
    id: 'task_04',
    title: 'Qualify inbound lead: David Sterling',
    description: 'Verify HyperScale Cloud Labs budget authorization and timeline.',
    type: 'follow_up',
    priority: 'high',
    status: 'pending',
    dueDate: '2026-09-26', // Today
    dueTime: '04:00 PM',
    assignedTo: 'usr_01',
    relatedToType: 'lead',
    relatedToId: 'lead_01',
    relatedToName: 'David Sterling (HyperScale Cloud Labs)',
    createdAt: '2026-09-25T09:00:00Z',
  },
  {
    id: 'task_05',
    title: 'Prepare Q3 Sales Performance Deck for Executive Board',
    description: 'Compile pipeline conversion, win/loss ratios, and forward ARR forecast.',
    type: 'demo',
    priority: 'medium',
    status: 'completed',
    dueDate: '2026-09-24',
    assignedTo: 'usr_01',
    completedAt: '2026-09-24T17:00:00Z',
    createdAt: '2026-09-20T09:00:00Z',
  },
];

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: 'act_01',
    type: 'call',
    title: 'Discovery call held with Sarah Chen',
    description: 'Sarah confirmed Vertex AI board approved the budget for Q4 deployment. Moving into final agreement stage.',
    performedBy: 'Alex Rivera',
    performedById: 'usr_01',
    timestamp: '2026-09-25T15:30:00Z',
    durationMinutes: 35,
    outcome: 'Successful - Stage shifted to Negotiation',
    relatedToType: 'deal',
    relatedToId: 'deal_01',
    relatedToName: 'Enterprise AI Suite Expansion',
  },
  {
    id: 'act_02',
    type: 'quotation_created',
    title: 'Quotation Q-2026-088 generated',
    description: 'Sent proposal breakdown totaling $85,000 to Marcus Vance at Apex Global Logistics.',
    performedBy: 'Alex Rivera',
    performedById: 'usr_01',
    timestamp: '2026-09-24T15:20:00Z',
    relatedToType: 'deal',
    relatedToId: 'deal_02',
    relatedToName: 'Global Fleet Automation Contract',
  },
  {
    id: 'act_03',
    type: 'deal_stage_changed',
    title: 'Cross-Border Clearing Gateway Closed Won!',
    description: 'Deal marked Closed Won after FinStream Payments signed master services agreement ($150,000 ARR).',
    performedBy: 'Alex Rivera',
    performedById: 'usr_01',
    timestamp: '2026-09-18T18:00:00Z',
    relatedToType: 'deal',
    relatedToId: 'deal_04',
    relatedToName: 'Cross-Border Clearing Gateway',
  },
  {
    id: 'act_04',
    type: 'meeting',
    title: 'Platform Architecture Demo with CyberShield Security',
    description: 'Demonstrated SSO, audit logs, and SOC2 compliance monitoring to Priya Sharma.',
    performedBy: 'Alex Rivera',
    performedById: 'usr_01',
    timestamp: '2026-09-17T11:00:00Z',
    durationMinutes: 45,
    outcome: 'Follow-up requested on custom roles',
    relatedToType: 'company',
    relatedToId: 'comp_05',
    relatedToName: 'CyberShield Security',
  },
  {
    id: 'act_05',
    type: 'email',
    title: 'Follow-up email sent to Nadia Kowalski',
    description: 'Sent calendar booking link and technical architecture whitepaper.',
    performedBy: 'Alex Rivera',
    performedById: 'usr_01',
    timestamp: '2026-09-22T09:40:00Z',
    relatedToType: 'lead',
    relatedToId: 'lead_02',
    relatedToName: 'Nadia Kowalski',
  },
];

export const INITIAL_SETTINGS: WorkspaceSettings = {
  companyName: 'Zan Technologies Inc.',
  defaultCurrency: 'USD',
  fiscalYearStart: 'January',
  timezone: 'America/New_York (EST)',
  emailNotifications: true,
  autoLeadScoring: true,
  twoFactorAuth: true,
};
