import {
  Company,
  Contact,
  Lead,
  Deal,
  Quotation,
  Task,
  Activity,
  Installation,
  InstallerScheduleItem,
  DeviceInventoryItem,
  ClientDeviceRequirement,
  DeviceStockItem,
} from '../types/crm';

// Dummy Companies
export const MOCK_COMPANIES: Company[] = [
  {
    id: 'comp_denver',
    name: 'Denver Commercial Center',
    domain: 'denvercommercial.io',
    industry: 'Commercial Facilities & Real Estate',
    size: '100-250',
    phone: '+1 (303) 555-0192',
    city: 'Denver',
    country: 'United States',
    totalRevenue: 38000000,
    openDealsCount: 2,
    createdAt: '2026-08-01T09:00:00.000Z',
  },
  {
    id: 'comp_1',
    name: 'AeroSpace Dynamics Ltd',
    domain: 'aerospacedynamics.io',
    industry: 'Aerospace & Defense',
    size: '250-500',
    phone: '+1 (555) 234-8901',
    city: 'Seattle',
    country: 'United States',
    totalRevenue: 45000000,
    openDealsCount: 1,
    createdAt: '2026-08-10T09:00:00.000Z',
  },
  {
    id: 'comp_2',
    name: 'NexGen Health Systems',
    domain: 'nexgenhealth.com',
    industry: 'Healthcare & Biotech',
    size: '500-1000',
    phone: '+1 (555) 876-5432',
    city: 'Boston',
    country: 'United States',
    totalRevenue: 82000000,
    openDealsCount: 1,
    createdAt: '2026-08-15T10:30:00.000Z',
  },
  {
    id: 'comp_3',
    name: 'Vertex FinTech Global',
    domain: 'vertexfin.ch',
    industry: 'Financial Services',
    size: '100-250',
    phone: '+41 22 789 4500',
    city: 'Geneva',
    country: 'Switzerland',
    totalRevenue: 28500000,
    openDealsCount: 1,
    createdAt: '2026-08-20T14:15:00.000Z',
  },
  {
    id: 'comp_4',
    name: 'Solaria Clean Energy Corp',
    domain: 'solariaenergy.de',
    industry: 'Renewable Energy',
    size: '50-100',
    phone: '+49 30 6543 2100',
    city: 'Berlin',
    country: 'Germany',
    totalRevenue: 14200000,
    openDealsCount: 1,
    createdAt: '2026-09-01T11:00:00.000Z',
  },
  {
    id: 'comp_5',
    name: 'HyperScale Logistics & IoT',
    domain: 'hyperscalelog.com',
    industry: 'Logistics & Supply Chain',
    size: '1000+',
    phone: '+65 6789 0123',
    city: 'Singapore',
    country: 'Singapore',
    totalRevenue: 120000000,
    openDealsCount: 1,
    createdAt: '2026-09-05T08:45:00.000Z',
  },
];

// 5 Dummy Contacts / Clients
export const MOCK_CONTACTS: Contact[] = [
  {
    id: 'cont_1',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@aerospacedynamics.io',
    phone: '+1 (555) 234-8910',
    title: 'Chief Operating Officer',
    companyId: 'comp_1',
    companyName: 'AeroSpace Dynamics Ltd',
    lifecycleStage: 'customer',
    lastActivityAt: '2026-09-29T08:15:00.000Z',
    assignedTo: 'usr_current',
    notes: 'Key executive stakeholder for automated plant operations.',
    createdAt: '2026-08-10T09:30:00.000Z',
  },
  {
    id: 'cont_2',
    name: 'Dr. Marcus Vance',
    email: 'm.vance@nexgenhealth.com',
    phone: '+1 (555) 876-5444',
    title: 'VP of Infrastructure & Facilities',
    companyId: 'comp_2',
    companyName: 'NexGen Health Systems',
    lifecycleStage: 'customer',
    lastActivityAt: '2026-09-29T07:30:00.000Z',
    assignedTo: 'usr_current',
    notes: 'Heading biomedical telemetry modernization initiative across regional centers.',
    createdAt: '2026-08-15T11:00:00.000Z',
  },
  {
    id: 'cont_3',
    name: 'Elena Rostova',
    email: 'elena.rostova@vertexfin.ch',
    phone: '+41 22 789 4512',
    title: 'Head of Digital Transformation',
    companyId: 'comp_3',
    companyName: 'Vertex FinTech Global',
    lifecycleStage: 'mql',
    lastActivityAt: '2026-09-27T14:00:00.000Z',
    assignedTo: 'usr_current',
    notes: 'Leading zero-trust gateway mesh integration for Swiss private cloud.',
    createdAt: '2026-08-20T14:45:00.000Z',
  },
  {
    id: 'cont_4',
    name: 'Lukas Weber',
    email: 'l.weber@solariaenergy.de',
    phone: '+49 30 6543 2118',
    title: 'Chief Technical Officer',
    companyId: 'comp_4',
    companyName: 'Solaria Clean Energy Corp',
    lifecycleStage: 'lead',
    lastActivityAt: '2026-09-28T15:00:00.000Z',
    assignedTo: 'usr_current',
    notes: 'Supervising smart grid telemetry devices across European solar parks.',
    createdAt: '2026-09-01T11:30:00.000Z',
  },
  {
    id: 'cont_5',
    name: 'Priya Sharma',
    email: 'priya.sharma@hyperscalelog.com',
    phone: '+65 6789 0145',
    title: 'Director of Global Operations',
    companyId: 'comp_5',
    companyName: 'HyperScale Logistics & IoT',
    lifecycleStage: 'customer',
    lastActivityAt: '2026-09-26T16:20:00.000Z',
    assignedTo: 'usr_current',
    notes: 'Oversees 300+ connected delivery vehicles in Southeast Asia.',
    createdAt: '2026-09-05T09:15:00.000Z',
  },
];

// 5 Dummy Enquiries / Leads
export const MOCK_LEADS: Lead[] = [
  {
    id: 'lead_1',
    name: 'David Chen',
    company: 'OmniRobotics AI',
    email: 'd.chen@omnirobotics.ai',
    phone: '+1 (555) 432-1098',
    source: 'website',
    status: 'new',
    score: 88,
    assignedTo: 'usr_current',
    estimatedValue: 45000,
    notes: 'Inbound enquiry via website product demo request. Wants autonomous facility telemetry sensors.',
    createdAt: '2026-09-28T10:15:00.000Z',
    updatedAt: '2026-09-28T10:15:00.000Z',
  },
  {
    id: 'lead_2',
    name: 'Amira Al-Mansoor',
    company: 'Gulf Smart Infrastructure',
    email: 'amira@gulfsmart.ae',
    phone: '+971 4 321 9876',
    source: 'linkedin',
    status: 'qualified',
    score: 94,
    assignedTo: 'usr_current',
    estimatedValue: 120000,
    notes: 'Evaluating enterprise IoT deployment across 12 commercial hubs in Dubai and Abu Dhabi.',
    createdAt: '2026-09-25T14:30:00.000Z',
    updatedAt: '2026-09-28T11:00:00.000Z',
  },
  {
    id: 'lead_3',
    name: 'Oliver Wright',
    company: 'EcoGrid Systems UK',
    email: 'o.wright@ecogrid.co.uk',
    phone: '+44 20 7946 0912',
    source: 'referral',
    status: 'discussion',
    score: 82,
    assignedTo: 'usr_current',
    estimatedValue: 68000,
    notes: 'Referred by Solaria Energy. Looking for turnkey installation support and sensor packages.',
    createdAt: '2026-09-22T09:00:00.000Z',
    updatedAt: '2026-09-27T16:00:00.000Z',
  },
  {
    id: 'lead_4',
    name: 'Claire Dubois',
    company: 'Lyon BioTech Innovations',
    email: 'claire.dubois@lyonbiotech.fr',
    phone: '+33 4 72 00 11 22',
    source: 'event',
    status: 'proposal',
    score: 91,
    assignedTo: 'usr_current',
    estimatedValue: 95000,
    notes: 'Met at Paris Tech Summit. Requested detailed quotation for clean-room telemetry nodes.',
    createdAt: '2026-09-18T13:45:00.000Z',
    updatedAt: '2026-09-26T12:00:00.000Z',
  },
  {
    id: 'lead_5',
    name: 'Kenji Takahashi',
    company: 'Nippon Data Center Group',
    email: 'takahashi.k@nippondc.jp',
    phone: '+81 3 5555 0143',
    source: 'cold_outreach',
    status: 'contacted',
    score: 76,
    assignedTo: 'usr_current',
    estimatedValue: 150000,
    notes: 'Introductory presentation delivered. Follow-up review scheduled for next week.',
    createdAt: '2026-09-15T08:00:00.000Z',
    updatedAt: '2026-09-24T09:30:00.000Z',
  },
];

// 7 Dummy Sales Deals across all 7 stages
export const MOCK_DEALS: Deal[] = [
  {
    id: 'deal_1',
    title: 'Enterprise Campus IoT Rollout',
    value: 185000,
    currency: 'USD',
    stage: 'won',
    probability: 100,
    expectedCloseDate: '2026-09-15',
    companyId: 'comp_1',
    companyName: 'AeroSpace Dynamics Ltd',
    contactId: 'cont_1',
    contactName: 'Sarah Jenkins',
    assignedTo: 'Tharik',
    priority: 'high',
    tags: ['Enterprise', 'Hardware + SLA'],
    createdAt: '2026-08-12T10:00:00.000Z',
    updatedAt: '2026-09-15T15:30:00.000Z',
  },
  {
    id: 'deal_2',
    title: 'Hospital Telemetry & Patient Sensor Grid',
    value: 140000,
    currency: 'USD',
    stage: 'negotiation',
    probability: 80,
    expectedCloseDate: '2026-10-15',
    companyId: 'comp_2',
    companyName: 'NexGen Health Systems',
    contactId: 'cont_2',
    contactName: 'Dr. Marcus Vance',
    assignedTo: 'Alex Rivera',
    priority: 'high',
    tags: ['Healthcare', 'Multi-Site'],
    createdAt: '2026-08-18T11:30:00.000Z',
    updatedAt: '2026-09-28T16:00:00.000Z',
  },
  {
    id: 'deal_3',
    title: 'Secure Financial Micro-Gateway Mesh',
    value: 92000,
    currency: 'USD',
    stage: 'proposal',
    probability: 50,
    expectedCloseDate: '2026-11-01',
    companyId: 'comp_3',
    companyName: 'Vertex FinTech Global',
    contactId: 'cont_3',
    contactName: 'Elena Rostova',
    assignedTo: 'Liam O\'Connor',
    priority: 'medium',
    tags: ['FinTech', 'Compliance'],
    createdAt: '2026-08-25T14:00:00.000Z',
    updatedAt: '2026-09-27T10:00:00.000Z',
  },
  {
    id: 'deal_4',
    title: 'Smart Solar Farm Monitoring Infrastructure',
    value: 64000,
    currency: 'USD',
    stage: 'cold',
    probability: 10,
    expectedCloseDate: '2026-11-20',
    companyId: 'comp_4',
    companyName: 'Solaria Clean Energy Corp',
    contactId: 'cont_4',
    contactName: 'Lukas Weber',
    assignedTo: 'Michael Chen',
    priority: 'medium',
    tags: ['Green Energy', 'Field Work'],
    createdAt: '2026-09-03T09:30:00.000Z',
    updatedAt: '2026-09-28T14:00:00.000Z',
  },
  {
    id: 'deal_5',
    title: 'Distribution Hub Fleet Telematics Upgrade',
    value: 210000,
    currency: 'USD',
    stage: 'new',
    probability: 20,
    expectedCloseDate: '2026-12-10',
    companyId: 'comp_5',
    companyName: 'HyperScale Logistics & IoT',
    contactId: 'cont_5',
    contactName: 'Priya Sharma',
    assignedTo: 'Tharik',
    priority: 'high',
    tags: ['Logistics', 'Fleet GPS'],
    createdAt: '2026-09-08T10:15:00.000Z',
    updatedAt: '2026-09-26T11:00:00.000Z',
  },
  {
    id: 'deal_6',
    title: 'Legacy Warehouse Optical Scanner Integration',
    value: 48000,
    currency: 'USD',
    stage: 'lost',
    probability: 0,
    expectedCloseDate: '2026-09-01',
    companyId: 'comp_1',
    companyName: 'AeroSpace Dynamics Ltd',
    contactId: 'cont_1',
    contactName: 'Sarah Jenkins',
    assignedTo: 'Alex Rivera',
    priority: 'low',
    tags: ['Hardware'],
    lostReason: 'Selected lower bidder with existing integration',
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-09-01T12:00:00.000Z',
  },
];

// 5 Dummy Quotations
export const MOCK_QUOTATIONS: Quotation[] = [
  {
    id: 'quot_1',
    quoteNumber: 'ZQ-2026-001',
    title: 'ZANI Facility Intelligence Platform Deployment',
    dealId: 'deal_1',
    dealTitle: 'Enterprise Campus IoT Rollout',
    contactName: 'Sarah Jenkins',
    contactEmail: 'sarah.jenkins@aerospacedynamics.io',
    companyName: 'AeroSpace Dynamics Ltd',
    status: 'accepted',
    issueDate: '2026-07-28',
    validUntil: '2026-08-27',
    lineItems: [
      { id: 'li_1', description: 'Dispenser sensor / machine tracking', quantity: 100, unitPrice: 0, unitOneTime: 0, unitMonthly: 5, discount: 0, amount: 0, oneTimeTotal: 0, monthlyTotal: 500 },
      { id: 'li_2', description: 'Gateway & LTE', quantity: 3, unitPrice: 0, unitOneTime: 0, unitMonthly: 30, discount: 0, amount: 0, oneTimeTotal: 0, monthlyTotal: 90 },
      { id: 'li_3', description: 'Installation + Travel', quantity: 1, unitPrice: 3000, unitOneTime: 3000, unitMonthly: 0, discount: 0, amount: 3000, oneTimeTotal: 3000, monthlyTotal: 0 },
      { id: 'li_4', description: 'Shipping', quantity: 1, unitPrice: 250, unitOneTime: 250, unitMonthly: 0, discount: 0, amount: 250, oneTimeTotal: 250, monthlyTotal: 0 },
      { id: 'li_5', description: 'ZANI License - LLM Platform with Data Agent only', quantity: 2, unitPrice: 0, unitOneTime: 0, unitMonthly: 120, discount: 0, amount: 0, oneTimeTotal: 0, monthlyTotal: 240 },
    ],
    subtotal: 3250,
    oneTimeSubtotal: 3250,
    monthlySubtotal: 830,
    annualRecurring: 9960,
    year1Total: 13210,
    taxRate: 0,
    taxAmount: 0,
    total: 3250,
    totalOneTime: 3250,
    totalMonthly: 830,
    terms: 'Pricing excludes applicable taxes. Recurring fees are billed monthly and include LTE connectivity, cloud hosting, and software updates.',
    notes: 'One-time charges cover hardware, shipping, installation, and travel as itemized above. Quote valid for the period stated above.',
    createdBy: 'Admin',
    createdAt: '2026-07-28T10:00:00.000Z',
  },
  {
    id: 'quot_2',
    quoteNumber: 'Q-2026-002',
    title: 'BioTelemetry Diagnostic Gateway Package',
    dealId: 'deal_2',
    dealTitle: 'Hospital Telemetry & Patient Sensor Grid',
    contactName: 'Dr. Marcus Vance',
    contactEmail: 'm.vance@nexgenhealth.com',
    companyName: 'NexGen Health Systems',
    status: 'sent',
    issueDate: '2026-09-22',
    validUntil: '2026-10-22',
    lineItems: [
      { id: 'li_4', description: 'Medical Grade Wireless Telemetry Transceivers', quantity: 80, unitPrice: 900, unitOneTime: 900, unitMonthly: 15, discount: 5, amount: 68400, oneTimeTotal: 68400, monthlyTotal: 1200 },
      { id: 'li_5', description: 'Encrypted Hospital Signal Repeater Hubs', quantity: 30, unitPrice: 800, unitOneTime: 800, unitMonthly: 20, discount: 0, amount: 24000, oneTimeTotal: 24000, monthlyTotal: 600 },
      { id: 'li_6', description: '24/7 Redundant Telemetry Cloud Monitoring (Annual)', quantity: 1, unitPrice: 34872, unitOneTime: 34872, unitMonthly: 850, discount: 0, amount: 34872, oneTimeTotal: 34872, monthlyTotal: 850 },
    ],
    subtotal: 127272,
    oneTimeSubtotal: 127272,
    monthlySubtotal: 2650,
    taxRate: 10,
    taxAmount: 12728,
    total: 140000,
    totalOneTime: 140000,
    totalMonthly: 2650,
    notes: 'Medical device ISO-13485 compliance certification included.',
    terms: '50% advance upon contract signing, 50% upon completed site commissioning.',
    createdBy: 'Admin',
    createdAt: '2026-09-22T14:30:00.000Z',
  },
  {
    id: 'quot_3',
    quoteNumber: 'Q-2026-003',
    title: 'FinTech Zero-Trust Sensor Array',
    dealId: 'deal_3',
    dealTitle: 'Secure Financial Micro-Gateway Mesh',
    contactName: 'Elena Rostova',
    contactEmail: 'elena.rostova@vertexfin.ch',
    companyName: 'Vertex FinTech Global',
    status: 'sent',
    issueDate: '2026-09-25',
    validUntil: '2026-10-25',
    lineItems: [
      { id: 'li_7', description: 'Tamper-Evident Sensor Nodes', quantity: 50, unitPrice: 750, unitOneTime: 750, unitMonthly: 10, discount: 0, amount: 37500, oneTimeTotal: 37500, monthlyTotal: 500 },
      { id: 'li_8', description: 'Hardware Cryptographic Data Firewall Bridges', quantity: 10, unitPrice: 2500, unitOneTime: 2500, unitMonthly: 80, discount: 0, amount: 25000, oneTimeTotal: 25000, monthlyTotal: 800 },
      { id: 'li_9', description: 'SOC-2 Compliance Security Audit Pack', quantity: 1, unitPrice: 21136, unitOneTime: 21136, unitMonthly: 450, discount: 0, amount: 21136, oneTimeTotal: 21136, monthlyTotal: 450 },
    ],
    subtotal: 83636,
    oneTimeSubtotal: 83636,
    monthlySubtotal: 1750,
    taxRate: 10,
    taxAmount: 8364,
    total: 92000,
    totalOneTime: 92000,
    totalMonthly: 1750,
    notes: 'Subject to FINMA compliance check and security review.',
    terms: 'Net 45 payment terms upon hardware delivery.',
    createdBy: 'Admin',
    createdAt: '2026-09-25T11:15:00.000Z',
  },
  {
    id: 'quot_4',
    quoteNumber: 'Q-2026-004',
    title: 'Photovoltaic Array Telematics Suite',
    dealId: 'deal_4',
    dealTitle: 'Smart Solar Farm Monitoring Infrastructure',
    contactName: 'Lukas Weber',
    contactEmail: 'l.weber@solariaenergy.de',
    companyName: 'Solaria Clean Energy Corp',
    status: 'draft',
    issueDate: '2026-09-28',
    validUntil: '2026-10-28',
    lineItems: [
      { id: 'li_10', description: 'Weatherproof Inverter Transponder Modules', quantity: 25, unitPrice: 1200, unitOneTime: 1200, unitMonthly: 18, discount: 0, amount: 30000, oneTimeTotal: 30000, monthlyTotal: 450 },
      { id: 'li_11', description: 'Solar Irradiance Weather Monitoring Stations', quantity: 5, unitPrice: 2500, unitOneTime: 2500, unitMonthly: 40, discount: 0, amount: 12500, oneTimeTotal: 12500, monthlyTotal: 200 },
      { id: 'li_12', description: 'Onsite Installation & Radio Signal Calibration', quantity: 1, unitPrice: 15681, unitOneTime: 15681, unitMonthly: 300, discount: 0, amount: 15681, oneTimeTotal: 15681, monthlyTotal: 300 },
    ],
    subtotal: 58181,
    oneTimeSubtotal: 58181,
    monthlySubtotal: 950,
    taxRate: 10,
    taxAmount: 5819,
    total: 64000,
    totalOneTime: 64000,
    totalMonthly: 950,
    notes: 'Includes IP67 outdoor ruggedized junction enclosures.',
    terms: '12-month standard maintenance warranty included.',
    createdBy: 'Admin',
    createdAt: '2026-09-28T09:00:00.000Z',
  },
  {
    id: 'quot_5',
    quoteNumber: 'Q-2026-005',
    title: 'Fleet GPS Tracking & Vehicle Diagnostic Units',
    dealId: 'deal_5',
    dealTitle: 'Distribution Hub Fleet Telematics Upgrade',
    contactName: 'Priya Sharma',
    contactEmail: 'priya.sharma@hyperscalelog.com',
    companyName: 'HyperScale Logistics & IoT',
    status: 'draft',
    issueDate: '2026-09-28',
    validUntil: '2026-10-31',
    lineItems: [
      { id: 'li_13', description: 'Heavy-Duty OBD-II Fleet GPS Transceivers', quantity: 300, unitPrice: 350, unitOneTime: 350, unitMonthly: 12, discount: 5, amount: 99750, oneTimeTotal: 99750, monthlyTotal: 3600 },
      { id: 'li_14', description: 'Central Hub Dispatcher Touchscreen Terminals', quantity: 10, unitPrice: 3500, unitOneTime: 3500, unitMonthly: 60, discount: 0, amount: 35000, oneTimeTotal: 35000, monthlyTotal: 600 },
      { id: 'li_15', description: 'Fleet Telematics Cloud API Enterprise License (1 Yr)', quantity: 1, unitPrice: 56159, unitOneTime: 56159, unitMonthly: 950, discount: 0, amount: 56159, oneTimeTotal: 56159, monthlyTotal: 950 },
    ],
    subtotal: 190909,
    oneTimeSubtotal: 190909,
    monthlySubtotal: 5150,
    taxRate: 10,
    taxAmount: 19091,
    total: 210000,
    totalOneTime: 210000,
    totalMonthly: 5150,
    notes: 'Installation in batches of 50 vehicles over weekend shifts.',
    terms: 'Yearly subscription renewal for cloud API after 12 months.',
    createdBy: 'Admin',
    createdAt: '2026-09-28T16:00:00.000Z',
  },
];

// 5 Dummy Operations: Installations (Includes today's date for live dashboard metrics)
export const MOCK_INSTALLATIONS: Installation[] = [
  {
    id: 'inst_1',
    customerId: 'cont_1',
    customerName: 'Sarah Jenkins',
    dealId: 'deal_1',
    dealTitle: 'Enterprise Campus IoT Rollout',
    bookingDate: '2026-09-20',
    installationDate: '2026-09-29', // Today!
    installer: 'Alex Rivera',
    status: 'completed',
    siteAddress: 'Building 4, 100 Industrial Parkway, Seattle, WA',
    contactPhone: '+1 (555) 234-8910',
    notes: 'Central gateway mounted and calibrated. Signal test verified at 99.8%. All 40 gateways active.',
    createdAt: '2026-09-20T10:00:00.000Z',
    updatedAt: '2026-09-29T11:30:00.000Z',
  },
  {
    id: 'inst_2',
    customerId: 'cont_2',
    customerName: 'Dr. Marcus Vance',
    dealId: 'deal_2',
    dealTitle: 'Hospital Telemetry & Patient Sensor Grid',
    bookingDate: '2026-09-25',
    installationDate: '2026-09-29', // Today!
    installer: 'Michael Chen',
    status: 'in_progress',
    siteAddress: 'Wing C, 450 Health Sciences Blvd, Boston, MA',
    contactPhone: '+1 (555) 876-5444',
    notes: 'Installation crew currently routing cables through secondary riser in Cardiology ward.',
    createdAt: '2026-09-25T14:00:00.000Z',
    updatedAt: '2026-09-29T13:00:00.000Z',
  },
  {
    id: 'inst_3',
    customerId: 'cont_3',
    customerName: 'Elena Rostova',
    dealId: 'deal_3',
    dealTitle: 'Secure Financial Micro-Gateway Mesh',
    bookingDate: '2026-09-27',
    installationDate: '2026-10-02',
    installer: 'Liam O\'Connor',
    status: 'scheduled',
    siteAddress: 'Rue du Rhône 42, 1204 Genève, Switzerland',
    contactPhone: '+41 22 789 4512',
    notes: 'Security clearance verified. Pre-installation hardware bench test passed with zero errors.',
    createdAt: '2026-09-27T09:30:00.000Z',
    updatedAt: '2026-09-27T09:30:00.000Z',
  },
  {
    id: 'inst_4',
    customerId: 'cont_4',
    customerName: 'Lukas Weber',
    dealId: 'deal_4',
    dealTitle: 'Smart Solar Farm Monitoring Infrastructure',
    bookingDate: '2026-09-28',
    installationDate: '2026-10-05',
    installer: 'Alex Rivera',
    status: 'pending',
    siteAddress: 'Solarfeld Ost 12, 14532 Kleinmachnow, Germany',
    contactPhone: '+49 30 6543 2118',
    notes: 'Awaiting delivery of specialized weatherproof brackets and cellular antennas.',
    createdAt: '2026-09-28T11:00:00.000Z',
    updatedAt: '2026-09-28T11:00:00.000Z',
  },
  {
    id: 'inst_5',
    customerId: 'cont_5',
    customerName: 'Priya Sharma',
    dealId: 'deal_5',
    dealTitle: 'Distribution Hub Fleet Telematics Upgrade',
    bookingDate: '2026-09-26',
    installationDate: '2026-10-08',
    installer: 'Daniel Wong',
    status: 'scheduled',
    siteAddress: '15 Pioneer Sector 1, Jurong, Singapore',
    contactPhone: '+65 6789 0145',
    notes: 'Batch #1 of 50 prime movers scheduled for weekend depot installation.',
    createdAt: '2026-09-26T15:20:00.000Z',
    updatedAt: '2026-09-26T15:20:00.000Z',
  },
];

// 5 Dummy Operations: Installer Schedule Slots
export const MOCK_INSTALLER_SCHEDULES: InstallerScheduleItem[] = [
  {
    id: 'sch_1',
    installer: 'Alex Rivera',
    siteVisitTime: '08:30 AM - 11:30 AM',
    visitDate: '2026-09-29', // Today!
    customerId: 'cont_1',
    customerName: 'Sarah Jenkins (AeroSpace Dynamics)',
    installationId: 'inst_1',
    status: 'completed',
    siteAddress: 'Building 4, 100 Industrial Parkway, Seattle, WA',
    notes: 'Gateway commissioning completed and handover document signed by facilities manager.',
    createdAt: '2026-09-20T10:30:00.000Z',
    updatedAt: '2026-09-29T11:30:00.000Z',
  },
  {
    id: 'sch_2',
    installer: 'Michael Chen',
    siteVisitTime: '01:00 PM - 04:30 PM',
    visitDate: '2026-09-29', // Today!
    customerId: 'cont_2',
    customerName: 'Dr. Marcus Vance (NexGen Health)',
    installationId: 'inst_2',
    status: 'in_progress',
    siteAddress: 'Wing C, 450 Health Sciences Blvd, Boston, MA',
    notes: 'Currently on-site running RF spectrum verification and transceiver placements.',
    createdAt: '2026-09-25T14:30:00.000Z',
    updatedAt: '2026-09-29T13:00:00.000Z',
  },
  {
    id: 'sch_3',
    installer: 'Liam O\'Connor',
    siteVisitTime: '09:00 AM - 12:00 PM',
    visitDate: '2026-10-02',
    customerId: 'cont_3',
    customerName: 'Elena Rostova (Vertex FinTech)',
    installationId: 'inst_3',
    status: 'confirmed',
    siteAddress: 'Rue du Rhône 42, 1204 Genève, Switzerland',
    notes: 'Escort and biometric badge registration ready at reception.',
    createdAt: '2026-09-27T10:00:00.000Z',
    updatedAt: '2026-09-27T10:00:00.000Z',
  },
  {
    id: 'sch_4',
    installer: 'Alex Rivera',
    siteVisitTime: '10:00 AM - 01:30 PM',
    visitDate: '2026-10-05',
    customerId: 'cont_4',
    customerName: 'Lukas Weber (Solaria Clean Energy)',
    installationId: 'inst_4',
    status: 'confirmed',
    siteAddress: 'Solarfeld Ost 12, 14532 Kleinmachnow, Germany',
    notes: 'Weather check confirms clear conditions for outdoor inverter mounting.',
    createdAt: '2026-09-28T11:30:00.000Z',
    updatedAt: '2026-09-28T11:30:00.000Z',
  },
  {
    id: 'sch_5',
    installer: 'Daniel Wong',
    siteVisitTime: '08:00 AM - 05:00 PM',
    visitDate: '2026-10-08',
    customerId: 'cont_5',
    customerName: 'Priya Sharma (HyperScale Logistics)',
    installationId: 'inst_5',
    status: 'confirmed',
    siteAddress: '15 Pioneer Sector 1, Jurong, Singapore',
    notes: 'Full-day scheduled slot to complete vehicle batch installation.',
    createdAt: '2026-09-26T16:00:00.000Z',
    updatedAt: '2026-09-26T16:00:00.000Z',
  },
];

// 5 Dummy Operations: Device Inventory
export const MOCK_DEVICE_INVENTORY: DeviceInventoryItem[] = [
  {
    id: 'dev_1',
    deviceName: 'Smart Industrial IoT Gateway (Pro)',
    category: 'IoT Gateways',
    sku: 'GW-PRO-900',
    requiredQty: 60,
    availableQty: 45,
    allocatedQty: 35,
    unit: 'units',
    updatedAt: '2026-09-29',
  },
  {
    id: 'dev_2',
    deviceName: 'Wireless Medical Telemetry Node',
    category: 'Medical Sensors',
    sku: 'MED-TEL-420',
    requiredQty: 120,
    availableQty: 80,
    allocatedQty: 65,
    unit: 'units',
    updatedAt: '2026-09-29',
  },
  {
    id: 'dev_3',
    deviceName: 'Encrypted Financial Hardware Bridge',
    category: 'Security Appliances',
    sku: 'SEC-BRG-10X',
    requiredQty: 25,
    availableQty: 30,
    allocatedQty: 15,
    unit: 'units',
    updatedAt: '2026-09-28',
  },
  {
    id: 'dev_4',
    deviceName: 'Weatherproof Solar Array Transponder',
    category: 'Environmental Sensors',
    sku: 'SOL-ENV-880',
    requiredQty: 50,
    availableQty: 70,
    allocatedQty: 25,
    unit: 'units',
    updatedAt: '2026-09-28',
  },
  {
    id: 'dev_5',
    deviceName: 'Heavy Duty OBD-II Fleet GPS Transceiver',
    category: 'Fleet Telematics',
    sku: 'FLT-GPS-300',
    requiredQty: 350,
    availableQty: 210,
    allocatedQty: 180,
    unit: 'units',
    updatedAt: '2026-09-27',
  },
];

// 5 Dummy Tasks & Follow-up Reminders
export const MOCK_TASKS: Task[] = [
  {
    id: 'task_1',
    title: 'Review Final Signed Contract with AeroSpace',
    description: 'Verify sign-off and confirm dispatch schedule for production campus gateway installation.',
    type: 'quote_review',
    priority: 'urgent',
    status: 'pending',
    dueDate: '2026-09-29', // Today!
    dueTime: '11:00 AM',
    assignedTo: 'usr_current',
    relatedToType: 'company',
    relatedToId: 'comp_1',
    relatedToName: 'AeroSpace Dynamics Ltd',
    createdAt: '2026-09-28T09:00:00.000Z',
  },
  {
    id: 'task_2',
    title: 'Clinical Validation Walkthrough Call',
    description: 'Review hospital telemetry installation progress with engineering and cardiology leads.',
    type: 'call',
    priority: 'high',
    status: 'pending',
    dueDate: '2026-09-29', // Today!
    dueTime: '02:30 PM',
    assignedTo: 'usr_current',
    relatedToType: 'contact',
    relatedToId: 'cont_2',
    relatedToName: 'Dr. Marcus Vance',
    createdAt: '2026-09-28T14:00:00.000Z',
  },
  {
    id: 'task_3',
    title: 'Executive Demo: OmniRobotics AI Facility Architecture',
    description: 'Present architecture diagram and live sensor dashboard to technical steering committee.',
    type: 'demo',
    priority: 'medium',
    status: 'pending',
    dueDate: '2026-09-30',
    dueTime: '10:00 AM',
    assignedTo: 'usr_current',
    relatedToType: 'lead',
    relatedToId: 'lead_1',
    relatedToName: 'David Chen (OmniRobotics)',
    createdAt: '2026-09-28T11:00:00.000Z',
  },
  {
    id: 'task_4',
    title: 'Follow-up on Proposal Q-2026-003',
    description: 'Send security compliance whitepaper and check for legal sign-off on gateway mesh.',
    type: 'email',
    priority: 'high',
    status: 'pending',
    dueDate: '2026-10-01',
    dueTime: '09:30 AM',
    assignedTo: 'usr_current',
    relatedToType: 'deal',
    relatedToId: 'deal_3',
    relatedToName: 'Secure Financial Micro-Gateway Mesh',
    createdAt: '2026-09-27T15:00:00.000Z',
  },
  {
    id: 'task_5',
    title: 'Quarterly Review & Solar Inverter Maintenance Sync',
    description: 'Finalized specification sheet for weatherproof transponder rollout.',
    type: 'meeting',
    priority: 'low',
    status: 'completed',
    dueDate: '2026-09-28',
    dueTime: '03:00 PM',
    assignedTo: 'usr_current',
    relatedToType: 'contact',
    relatedToId: 'cont_4',
    relatedToName: 'Lukas Weber',
    completedAt: '2026-09-28T16:00:00.000Z',
    createdAt: '2026-09-25T11:00:00.000Z',
  },
];

// 5 Dummy Activities (Timeline Feed)
export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: 'act_1',
    type: 'deal_stage_changed',
    title: 'Deal "Enterprise Campus IoT Rollout" moved to CLOSED WON',
    description: 'Probability set to 100%. Total closed contract value: $185,000.',
    performedBy: 'Admin',
    performedById: 'usr_current',
    timestamp: '2026-09-29T08:15:00.000Z',
    relatedToType: 'deal',
    relatedToId: 'deal_1',
    relatedToName: 'Enterprise Campus IoT Rollout',
  },
  {
    id: 'act_2',
    type: 'quotation_created',
    title: 'Quotation Q-2026-002 created & dispatched',
    description: 'For NexGen Health Systems (Dr. Marcus Vance) amounting to $140,000.',
    performedBy: 'Admin',
    performedById: 'usr_current',
    timestamp: '2026-09-28T16:30:00.000Z',
    relatedToType: 'deal',
    relatedToId: 'deal_2',
    relatedToName: 'Hospital Telemetry & Patient Sensor Grid',
  },
  {
    id: 'act_3',
    type: 'call',
    title: 'Discovery Call with Amira Al-Mansoor',
    description: 'Discussed 12-site commercial rollout. Client requested customized SLA proposal.',
    performedBy: 'Admin',
    performedById: 'usr_current',
    timestamp: '2026-09-28T11:00:00.000Z',
    durationMinutes: 35,
    outcome: 'Qualified lead and scheduled technical deep-dive.',
    relatedToType: 'lead',
    relatedToId: 'lead_2',
    relatedToName: 'Amira Al-Mansoor',
  },
  {
    id: 'act_4',
    type: 'meeting',
    title: 'Geneva Data Center Architectural Review',
    description: 'Reviewed zero-trust firewall compliance and server rack physical constraints.',
    performedBy: 'Admin',
    performedById: 'usr_current',
    timestamp: '2026-09-27T14:00:00.000Z',
    durationMinutes: 60,
    outcome: 'Approved hardware specifications and site security clearance.',
    relatedToType: 'deal',
    relatedToId: 'deal_3',
    relatedToName: 'Vertex FinTech Global',
  },
  {
    id: 'act_5',
    type: 'note',
    title: 'Technical Note: Photovoltaic Telemetry Specs',
    description: 'Lukas confirmed requirement for IP67 weatherproof casing and cellular failover.',
    performedBy: 'Admin',
    performedById: 'usr_current',
    timestamp: '2026-09-26T09:45:00.000Z',
    relatedToType: 'contact',
    relatedToId: 'cont_4',
    relatedToName: 'Lukas Weber',
  },
];

// Device Definitions for Client Requirements
export interface DeviceDefinition {
  key: string;
  name: string;
  description: string;
  defaultIndiaStock: number;
}

export const DEVICE_DEFINITIONS: DeviceDefinition[] = [
  {
    key: 'toilet_paper',
    name: 'Toilet paper',
    description: 'Roll level sensor',
    defaultIndiaStock: 10,
  },
  {
    key: 'paper_towel',
    name: 'Paper towel',
    description: 'Towel level sensor',
    defaultIndiaStock: 5,
  },
  {
    key: 'trash',
    name: 'Trash',
    description: 'Bin fill sensor',
    defaultIndiaStock: 25,
  },
  {
    key: 'ros',
    name: 'ROS',
    description: 'Restroom occupancy sensor',
    defaultIndiaStock: 30,
  },
  {
    key: 'stall',
    name: 'Stall',
    description: 'Stall door sensor',
    defaultIndiaStock: 40,
  },
  {
    key: 'stall_ros',
    name: 'Stall ROS',
    description: 'Stall occupancy sensor',
    defaultIndiaStock: 35,
  },
  {
    key: 'air_quality',
    name: 'Air quality',
    description: 'Odor and air sensor',
    defaultIndiaStock: 20,
  },
  {
    key: 'gateway',
    name: 'Gateway',
    description: 'Gateway',
    defaultIndiaStock: 15,
  },
  {
    key: 'battery_pack',
    name: 'Battery pack',
    description: 'Battery pack',
    defaultIndiaStock: 50,
  },
  {
    key: 'soap_dispenser',
    name: 'Soap dispenser',
    description: 'Soap dispenser',
    defaultIndiaStock: 35,
  },
];

// Mock Device Stock for India Production and US Warehouse
export const MOCK_DEVICE_STOCK: DeviceStockItem[] = [
  {
    id: 'stock_toilet_paper',
    deviceKey: 'toilet_paper',
    deviceName: 'Toilet paper',
    deviceDescription: 'Roll level sensor',
    usWarehouse: 20,
    indiaProduction: 45,
    updatedAt: '2026-09-30T12:00:00.000Z',
  },
  {
    id: 'stock_paper_towel',
    deviceKey: 'paper_towel',
    deviceName: 'Paper towel',
    deviceDescription: 'Towel level sensor',
    usWarehouse: 15,
    indiaProduction: 25,
    updatedAt: '2026-09-30T12:00:00.000Z',
  },
  {
    id: 'stock_trash',
    deviceKey: 'trash',
    deviceName: 'Trash',
    deviceDescription: 'Bin fill sensor',
    usWarehouse: 18,
    indiaProduction: 25,
    updatedAt: '2026-09-30T12:00:00.000Z',
  },
  {
    id: 'stock_ros',
    deviceKey: 'ros',
    deviceName: 'ROS',
    deviceDescription: 'Restroom occupancy sensor',
    usWarehouse: 12,
    indiaProduction: 30,
    updatedAt: '2026-09-30T12:00:00.000Z',
  },
  {
    id: 'stock_stall',
    deviceKey: 'stall',
    deviceName: 'Stall',
    deviceDescription: 'Stall door sensor',
    usWarehouse: 25,
    indiaProduction: 40,
    updatedAt: '2026-09-30T12:00:00.000Z',
  },
  {
    id: 'stock_stall_ros',
    deviceKey: 'stall_ros',
    deviceName: 'Stall ROS',
    deviceDescription: 'Stall occupancy sensor',
    usWarehouse: 20,
    indiaProduction: 35,
    updatedAt: '2026-09-30T12:00:00.000Z',
  },
  {
    id: 'stock_air_quality',
    deviceKey: 'air_quality',
    deviceName: 'Air quality',
    deviceDescription: 'Odor and air sensor',
    usWarehouse: 10,
    indiaProduction: 20,
    updatedAt: '2026-09-30T12:00:00.000Z',
  },
  {
    id: 'stock_gateway',
    deviceKey: 'gateway',
    deviceName: 'Gateway',
    deviceDescription: 'Gateway',
    usWarehouse: 8,
    indiaProduction: 15,
    updatedAt: '2026-09-30T12:00:00.000Z',
  },
  {
    id: 'stock_battery_pack',
    deviceKey: 'battery_pack',
    deviceName: 'Battery pack',
    deviceDescription: 'Battery pack',
    usWarehouse: 30,
    indiaProduction: 50,
    updatedAt: '2026-09-30T12:00:00.000Z',
  },
  {
    id: 'stock_soap_dispenser',
    deviceKey: 'soap_dispenser',
    deviceName: 'Soap dispenser',
    deviceDescription: 'Soap dispenser',
    usWarehouse: 22,
    indiaProduction: 35,
    updatedAt: '2026-09-30T12:00:00.000Z',
  },
];


// Mock Client Requirements per Company ID
export const MOCK_CLIENT_REQUIREMENTS: Record<string, ClientDeviceRequirement[]> = {
  comp_denver: [
    {
      id: 'req_denver_1',
      clientId: 'comp_denver',
      deviceKey: 'toilet_paper',
      deviceName: 'Toilet paper',
      deviceDescription: 'Roll level sensor',
      required: 25,
      installed: 18,
      indiaStock: 10,
      updatedAt: '2026-09-30T10:00:00.000Z',
    },
    {
      id: 'req_denver_2',
      clientId: 'comp_denver',
      deviceKey: 'paper_towel',
      deviceName: 'Paper towel',
      deviceDescription: 'Towel level sensor',
      required: 20,
      installed: 10,
      indiaStock: 5,
      updatedAt: '2026-09-30T10:00:00.000Z',
    },
    {
      id: 'req_denver_3',
      clientId: 'comp_denver',
      deviceKey: 'trash',
      deviceName: 'Trash',
      deviceDescription: 'Bin fill sensor',
      required: 15,
      installed: 10,
      indiaStock: 20,
      updatedAt: '2026-09-30T10:00:00.000Z',
    },
    {
      id: 'req_denver_4',
      clientId: 'comp_denver',
      deviceKey: 'ros',
      deviceName: 'ROS',
      deviceDescription: 'Restroom occupancy sensor',
      required: 12,
      installed: 8,
      indiaStock: 15,
      updatedAt: '2026-09-30T10:00:00.000Z',
    },
    {
      id: 'req_denver_5',
      clientId: 'comp_denver',
      deviceKey: 'stall',
      deviceName: 'Stall',
      deviceDescription: 'Stall door sensor',
      required: 20,
      installed: 14,
      indiaStock: 25,
      updatedAt: '2026-09-30T10:00:00.000Z',
    },
    {
      id: 'req_denver_6',
      clientId: 'comp_denver',
      deviceKey: 'stall_ros',
      deviceName: 'Stall ROS',
      deviceDescription: 'Stall occupancy sensor',
      required: 16,
      installed: 12,
      indiaStock: 30,
      updatedAt: '2026-09-30T10:00:00.000Z',
    },
    {
      id: 'req_denver_7',
      clientId: 'comp_denver',
      deviceKey: 'air_quality',
      deviceName: 'Air quality',
      deviceDescription: 'Odor and air sensor',
      required: 8,
      installed: 6,
      indiaStock: 8,
      updatedAt: '2026-09-30T10:00:00.000Z',
    },
    {
      id: 'req_denver_8',
      clientId: 'comp_denver',
      deviceKey: 'gateway',
      deviceName: 'Gateway',
      deviceDescription: 'Gateway',
      required: 4,
      installed: 4,
      indiaStock: 10,
      updatedAt: '2026-09-30T10:00:00.000Z',
    },
    {
      id: 'req_denver_9',
      clientId: 'comp_denver',
      deviceKey: 'battery_pack',
      deviceName: 'Battery pack',
      deviceDescription: 'Battery pack',
      required: 25,
      installed: 15,
      indiaStock: 50,
      updatedAt: '2026-09-30T10:00:00.000Z',
    },
    {
      id: 'req_denver_10',
      clientId: 'comp_denver',
      deviceKey: 'soap_dispenser',
      deviceName: 'Soap dispenser',
      deviceDescription: 'Soap dispenser',
      required: 20,
      installed: 10,
      indiaStock: 35,
      updatedAt: '2026-09-30T10:00:00.000Z',
    },
  ],
  comp_1: [
    {
      id: 'req_comp1_1',
      clientId: 'comp_1',
      deviceKey: 'toilet_paper',
      deviceName: 'Toilet paper',
      deviceDescription: 'Roll level sensor',
      required: 30,
      installed: 28,
      indiaStock: 45,
      updatedAt: '2026-09-28T09:00:00.000Z',
    },
    {
      id: 'req_comp1_2',
      clientId: 'comp_1',
      deviceKey: 'paper_towel',
      deviceName: 'Paper towel',
      deviceDescription: 'Towel level sensor',
      required: 25,
      installed: 22,
      indiaStock: 30,
      updatedAt: '2026-09-28T09:00:00.000Z',
    },
    {
      id: 'req_comp1_3',
      clientId: 'comp_1',
      deviceKey: 'trash',
      deviceName: 'Trash',
      deviceDescription: 'Bin fill sensor',
      required: 18,
      installed: 16,
      indiaStock: 25,
      updatedAt: '2026-09-28T09:00:00.000Z',
    },
    {
      id: 'req_comp1_4',
      clientId: 'comp_1',
      deviceKey: 'ros',
      deviceName: 'ROS',
      deviceDescription: 'Restroom occupancy sensor',
      required: 14,
      installed: 12,
      indiaStock: 20,
      updatedAt: '2026-09-28T09:00:00.000Z',
    },
    {
      id: 'req_comp1_5',
      clientId: 'comp_1',
      deviceKey: 'stall',
      deviceName: 'Stall',
      deviceDescription: 'Stall door sensor',
      required: 24,
      installed: 20,
      indiaStock: 35,
      updatedAt: '2026-09-28T09:00:00.000Z',
    },
    {
      id: 'req_comp1_6',
      clientId: 'comp_1',
      deviceKey: 'stall_ros',
      deviceName: 'Stall ROS',
      deviceDescription: 'Stall occupancy sensor',
      required: 20,
      installed: 18,
      indiaStock: 28,
      updatedAt: '2026-09-28T09:00:00.000Z',
    },
    {
      id: 'req_comp1_7',
      clientId: 'comp_1',
      deviceKey: 'air_quality',
      deviceName: 'Air quality',
      deviceDescription: 'Odor and air sensor',
      required: 12,
      installed: 10,
      indiaStock: 18,
      updatedAt: '2026-09-28T09:00:00.000Z',
    },
    {
      id: 'req_comp1_8',
      clientId: 'comp_1',
      deviceKey: 'gateway',
      deviceName: 'Gateway',
      deviceDescription: 'Gateway',
      required: 5,
      installed: 4,
      indiaStock: 12,
      updatedAt: '2026-09-28T09:00:00.000Z',
    },
    {
      id: 'req_comp1_9',
      clientId: 'comp_1',
      deviceKey: 'battery_pack',
      deviceName: 'Battery pack',
      deviceDescription: 'Battery pack',
      required: 18,
      installed: 12,
      indiaStock: 50,
      updatedAt: '2026-09-28T09:00:00.000Z',
    },
    {
      id: 'req_comp1_10',
      clientId: 'comp_1',
      deviceKey: 'soap_dispenser',
      deviceName: 'Soap dispenser',
      deviceDescription: 'Soap dispenser',
      required: 14,
      installed: 9,
      indiaStock: 35,
      updatedAt: '2026-09-28T09:00:00.000Z',
    },
  ],
  comp_2: [
    {
      id: 'req_comp2_1',
      clientId: 'comp_2',
      deviceKey: 'toilet_paper',
      deviceName: 'Toilet paper',
      deviceDescription: 'Roll level sensor',
      required: 40,
      installed: 20,
      indiaStock: 35,
      updatedAt: '2026-09-27T11:00:00.000Z',
    },
    {
      id: 'req_comp2_2',
      clientId: 'comp_2',
      deviceKey: 'paper_towel',
      deviceName: 'Paper towel',
      deviceDescription: 'Towel level sensor',
      required: 35,
      installed: 15,
      indiaStock: 15,
      updatedAt: '2026-09-27T11:00:00.000Z',
    },
    {
      id: 'req_comp2_3',
      clientId: 'comp_2',
      deviceKey: 'trash',
      deviceName: 'Trash',
      deviceDescription: 'Bin fill sensor',
      required: 20,
      installed: 10,
      indiaStock: 12,
      updatedAt: '2026-09-27T11:00:00.000Z',
    },
    {
      id: 'req_comp2_4',
      clientId: 'comp_2',
      deviceKey: 'ros',
      deviceName: 'ROS',
      deviceDescription: 'Restroom occupancy sensor',
      required: 18,
      installed: 9,
      indiaStock: 10,
      updatedAt: '2026-09-27T11:00:00.000Z',
    },
    {
      id: 'req_comp2_5',
      clientId: 'comp_2',
      deviceKey: 'stall',
      deviceName: 'Stall',
      deviceDescription: 'Stall door sensor',
      required: 30,
      installed: 15,
      indiaStock: 20,
      updatedAt: '2026-09-27T11:00:00.000Z',
    },
    {
      id: 'req_comp2_6',
      clientId: 'comp_2',
      deviceKey: 'stall_ros',
      deviceName: 'Stall ROS',
      deviceDescription: 'Stall occupancy sensor',
      required: 24,
      installed: 12,
      indiaStock: 15,
      updatedAt: '2026-09-27T11:00:00.000Z',
    },
    {
      id: 'req_comp2_7',
      clientId: 'comp_2',
      deviceKey: 'air_quality',
      deviceName: 'Air quality',
      deviceDescription: 'Odor and air sensor',
      required: 15,
      installed: 8,
      indiaStock: 6,
      updatedAt: '2026-09-27T11:00:00.000Z',
    },
    {
      id: 'req_comp2_8',
      clientId: 'comp_2',
      deviceKey: 'gateway',
      deviceName: 'Gateway',
      deviceDescription: 'Gateway',
      required: 6,
      installed: 3,
      indiaStock: 8,
      updatedAt: '2026-09-27T11:00:00.000Z',
    },
    {
      id: 'req_comp2_9',
      clientId: 'comp_2',
      deviceKey: 'battery_pack',
      deviceName: 'Battery pack',
      deviceDescription: 'Battery pack',
      required: 30,
      installed: 15,
      indiaStock: 50,
      updatedAt: '2026-09-27T11:00:00.000Z',
    },
    {
      id: 'req_comp2_10',
      clientId: 'comp_2',
      deviceKey: 'soap_dispenser',
      deviceName: 'Soap dispenser',
      deviceDescription: 'Soap dispenser',
      required: 22,
      installed: 12,
      indiaStock: 35,
      updatedAt: '2026-09-27T11:00:00.000Z',
    },
  ],
  comp_3: [
    {
      id: 'req_comp3_1',
      clientId: 'comp_3',
      deviceKey: 'toilet_paper',
      deviceName: 'Toilet paper',
      deviceDescription: 'Roll level sensor',
      required: 20,
      installed: 18,
      indiaStock: 25,
      updatedAt: '2026-09-25T14:00:00.000Z',
    },
    {
      id: 'req_comp3_2',
      clientId: 'comp_3',
      deviceKey: 'paper_towel',
      deviceName: 'Paper towel',
      deviceDescription: 'Towel level sensor',
      required: 16,
      installed: 15,
      indiaStock: 20,
      updatedAt: '2026-09-25T14:00:00.000Z',
    },
    {
      id: 'req_comp3_3',
      clientId: 'comp_3',
      deviceKey: 'trash',
      deviceName: 'Trash',
      deviceDescription: 'Bin fill sensor',
      required: 10,
      installed: 9,
      indiaStock: 15,
      updatedAt: '2026-09-25T14:00:00.000Z',
    },
    {
      id: 'req_comp3_4',
      clientId: 'comp_3',
      deviceKey: 'ros',
      deviceName: 'ROS',
      deviceDescription: 'Restroom occupancy sensor',
      required: 8,
      installed: 7,
      indiaStock: 12,
      updatedAt: '2026-09-25T14:00:00.000Z',
    },
    {
      id: 'req_comp3_5',
      clientId: 'comp_3',
      deviceKey: 'stall',
      deviceName: 'Stall',
      deviceDescription: 'Stall door sensor',
      required: 14,
      installed: 13,
      indiaStock: 18,
      updatedAt: '2026-09-25T14:00:00.000Z',
    },
    {
      id: 'req_comp3_6',
      clientId: 'comp_3',
      deviceKey: 'stall_ros',
      deviceName: 'Stall ROS',
      deviceDescription: 'Stall occupancy sensor',
      required: 12,
      installed: 11,
      indiaStock: 16,
      updatedAt: '2026-09-25T14:00:00.000Z',
    },
    {
      id: 'req_comp3_7',
      clientId: 'comp_3',
      deviceKey: 'air_quality',
      deviceName: 'Air quality',
      deviceDescription: 'Odor and air sensor',
      required: 6,
      installed: 5,
      indiaStock: 10,
      updatedAt: '2026-09-25T14:00:00.000Z',
    },
    {
      id: 'req_comp3_8',
      clientId: 'comp_3',
      deviceKey: 'gateway',
      deviceName: 'Gateway',
      deviceDescription: 'Gateway',
      required: 3,
      installed: 3,
      indiaStock: 8,
      updatedAt: '2026-09-25T14:00:00.000Z',
    },
    {
      id: 'req_comp3_9',
      clientId: 'comp_3',
      deviceKey: 'battery_pack',
      deviceName: 'Battery pack',
      deviceDescription: 'Battery pack',
      required: 15,
      installed: 12,
      indiaStock: 50,
      updatedAt: '2026-09-25T14:00:00.000Z',
    },
    {
      id: 'req_comp3_10',
      clientId: 'comp_3',
      deviceKey: 'soap_dispenser',
      deviceName: 'Soap dispenser',
      deviceDescription: 'Soap dispenser',
      required: 12,
      installed: 10,
      indiaStock: 35,
      updatedAt: '2026-09-25T14:00:00.000Z',
    },
  ],
  comp_4: [
    {
      id: 'req_comp4_1',
      clientId: 'comp_4',
      deviceKey: 'toilet_paper',
      deviceName: 'Toilet paper',
      deviceDescription: 'Roll level sensor',
      required: 18,
      installed: 6,
      indiaStock: 30,
      updatedAt: '2026-09-26T12:00:00.000Z',
    },
    {
      id: 'req_comp4_2',
      clientId: 'comp_4',
      deviceKey: 'paper_towel',
      deviceName: 'Paper towel',
      deviceDescription: 'Towel level sensor',
      required: 14,
      installed: 5,
      indiaStock: 25,
      updatedAt: '2026-09-26T12:00:00.000Z',
    },
    {
      id: 'req_comp4_3',
      clientId: 'comp_4',
      deviceKey: 'trash',
      deviceName: 'Trash',
      deviceDescription: 'Bin fill sensor',
      required: 10,
      installed: 4,
      indiaStock: 15,
      updatedAt: '2026-09-26T12:00:00.000Z',
    },
    {
      id: 'req_comp4_4',
      clientId: 'comp_4',
      deviceKey: 'ros',
      deviceName: 'ROS',
      deviceDescription: 'Restroom occupancy sensor',
      required: 8,
      installed: 3,
      indiaStock: 10,
      updatedAt: '2026-09-26T12:00:00.000Z',
    },
    {
      id: 'req_comp4_5',
      clientId: 'comp_4',
      deviceKey: 'stall',
      deviceName: 'Stall',
      deviceDescription: 'Stall door sensor',
      required: 12,
      installed: 5,
      indiaStock: 20,
      updatedAt: '2026-09-26T12:00:00.000Z',
    },
    {
      id: 'req_comp4_6',
      clientId: 'comp_4',
      deviceKey: 'stall_ros',
      deviceName: 'Stall ROS',
      deviceDescription: 'Stall occupancy sensor',
      required: 10,
      installed: 4,
      indiaStock: 15,
      updatedAt: '2026-09-26T12:00:00.000Z',
    },
    {
      id: 'req_comp4_7',
      clientId: 'comp_4',
      deviceKey: 'air_quality',
      deviceName: 'Air quality',
      deviceDescription: 'Odor and air sensor',
      required: 6,
      installed: 2,
      indiaStock: 8,
      updatedAt: '2026-09-26T12:00:00.000Z',
    },
    {
      id: 'req_comp4_8',
      clientId: 'comp_4',
      deviceKey: 'gateway',
      deviceName: 'Gateway',
      deviceDescription: 'Gateway',
      required: 3,
      installed: 1,
      indiaStock: 6,
      updatedAt: '2026-09-26T12:00:00.000Z',
    },
    {
      id: 'req_comp4_9',
      clientId: 'comp_4',
      deviceKey: 'battery_pack',
      deviceName: 'Battery pack',
      deviceDescription: 'Battery pack',
      required: 12,
      installed: 5,
      indiaStock: 50,
      updatedAt: '2026-09-26T12:00:00.000Z',
    },
    {
      id: 'req_comp4_10',
      clientId: 'comp_4',
      deviceKey: 'soap_dispenser',
      deviceName: 'Soap dispenser',
      deviceDescription: 'Soap dispenser',
      required: 10,
      installed: 4,
      indiaStock: 35,
      updatedAt: '2026-09-26T12:00:00.000Z',
    },
  ],
  comp_5: [
    {
      id: 'req_comp5_1',
      clientId: 'comp_5',
      deviceKey: 'toilet_paper',
      deviceName: 'Toilet paper',
      deviceDescription: 'Roll level sensor',
      required: 35,
      installed: 28,
      indiaStock: 50,
      updatedAt: '2026-09-29T15:00:00.000Z',
    },
    {
      id: 'req_comp5_2',
      clientId: 'comp_5',
      deviceKey: 'paper_towel',
      deviceName: 'Paper towel',
      deviceDescription: 'Towel level sensor',
      required: 30,
      installed: 22,
      indiaStock: 40,
      updatedAt: '2026-09-29T15:00:00.000Z',
    },
    {
      id: 'req_comp5_3',
      clientId: 'comp_5',
      deviceKey: 'trash',
      deviceName: 'Trash',
      deviceDescription: 'Bin fill sensor',
      required: 20,
      installed: 15,
      indiaStock: 30,
      updatedAt: '2026-09-29T15:00:00.000Z',
    },
    {
      id: 'req_comp5_4',
      clientId: 'comp_5',
      deviceKey: 'ros',
      deviceName: 'ROS',
      deviceDescription: 'Restroom occupancy sensor',
      required: 15,
      installed: 12,
      indiaStock: 25,
      updatedAt: '2026-09-29T15:00:00.000Z',
    },
    {
      id: 'req_comp5_5',
      clientId: 'comp_5',
      deviceKey: 'stall',
      deviceName: 'Stall',
      deviceDescription: 'Stall door sensor',
      required: 25,
      installed: 18,
      indiaStock: 35,
      updatedAt: '2026-09-29T15:00:00.000Z',
    },
    {
      id: 'req_comp5_6',
      clientId: 'comp_5',
      deviceKey: 'stall_ros',
      deviceName: 'Stall ROS',
      deviceDescription: 'Stall occupancy sensor',
      required: 20,
      installed: 15,
      indiaStock: 30,
      updatedAt: '2026-09-29T15:00:00.000Z',
    },
    {
      id: 'req_comp5_7',
      clientId: 'comp_5',
      deviceKey: 'air_quality',
      deviceName: 'Air quality',
      deviceDescription: 'Odor and air sensor',
      required: 12,
      installed: 9,
      indiaStock: 20,
      updatedAt: '2026-09-29T15:00:00.000Z',
    },
    {
      id: 'req_comp5_8',
      clientId: 'comp_5',
      deviceKey: 'gateway',
      deviceName: 'Gateway',
      deviceDescription: 'Gateway',
      required: 5,
      installed: 4,
      indiaStock: 15,
      updatedAt: '2026-09-29T15:00:00.000Z',
    },
    {
      id: 'req_comp5_9',
      clientId: 'comp_5',
      deviceKey: 'battery_pack',
      deviceName: 'Battery pack',
      deviceDescription: 'Battery pack',
      required: 25,
      installed: 18,
      indiaStock: 50,
      updatedAt: '2026-09-29T15:00:00.000Z',
    },
    {
      id: 'req_comp5_10',
      clientId: 'comp_5',
      deviceKey: 'soap_dispenser',
      deviceName: 'Soap dispenser',
      deviceDescription: 'Soap dispenser',
      required: 18,
      installed: 12,
      indiaStock: 35,
      updatedAt: '2026-09-29T15:00:00.000Z',
    },
  ],
};
