import {
  Company,
  Contact,
  Lead,
  Deal,
  Quotation,
  Task,
  Activity,
  Installation,
  InstallerScheduleItem,
  DeviceInventoryItem,
} from '../types/crm';

// 5 Dummy Companies
export const MOCK_COMPANIES: Company[] = [
  {
    id: 'comp_1',
    name: 'AeroSpace Dynamics Ltd',
    domain: 'aerospacedynamics.io',
    industry: 'Aerospace & Defense',
    size: '250-500',
    phone: '+1 (555) 234-8901',
    city: 'Seattle',
    country: 'United States',
    totalRevenue: 45000000,
    openDealsCount: 1,
    createdAt: '2026-08-10T09:00:00.000Z',
  },
  {
    id: 'comp_2',
    name: 'NexGen Health Systems',
    domain: 'nexgenhealth.com',
    industry: 'Healthcare & Biotech',
    size: '500-1000',
    phone: '+1 (555) 876-5432',
    city: 'Boston',
    country: 'United States',
    totalRevenue: 82000000,
    openDealsCount: 1,
    createdAt: '2026-08-15T10:30:00.000Z',
  },
  {
    id: 'comp_3',
    name: 'Vertex FinTech Global',
    domain: 'vertexfin.ch',
    industry: 'Financial Services',
    size: '100-250',
    phone: '+41 22 789 4500',
    city: 'Geneva',
    country: 'Switzerland',
    totalRevenue: 28500000,
    openDealsCount: 1,
    createdAt: '2026-08-20T14:15:00.000Z',
  },
  {
    id: 'comp_4',
    name: 'Solaria Clean Energy Corp',
    domain: 'solariaenergy.de',
    industry: 'Renewable Energy',
    size: '50-100',
    phone: '+49 30 6543 2100',
    city: 'Berlin',
    country: 'Germany',
    totalRevenue: 14200000,
    openDealsCount: 1,
    createdAt: '2026-09-01T11:00:00.000Z',
  },
  {
    id: 'comp_5',
    name: 'HyperScale Logistics & IoT',
    domain: 'hyperscalelog.com',
    industry: 'Logistics & Supply Chain',
    size: '1000+',
    phone: '+65 6789 0123',
    city: 'Singapore',
    country: 'Singapore',
    totalRevenue: 120000000,
    openDealsCount: 1,
    createdAt: '2026-09-05T08:45:00.000Z',
  },
];

// 5 Dummy Contacts / Clients
export const MOCK_CONTACTS: Contact[] = [
  {
    id: 'cont_1',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@aerospacedynamics.io',
    phone: '+1 (555) 234-8910',
    title: 'Chief Operating Officer',
    companyId: 'comp_1',
    companyName: 'AeroSpace Dynamics Ltd',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    lifecycleStage: 'customer',
    lastActivityAt: '2026-09-29T08:15:00.000Z',
    assignedTo: 'usr_current',
    notes: 'Key executive stakeholder for automated plant operations.',
    createdAt: '2026-08-10T09:30:00.000Z',
  },
  {
    id: 'cont_2',
    name: 'Dr. Marcus Vance',
    email: 'm.vance@nexgenhealth.com',
    phone: '+1 (555) 876-5444',
    title: 'VP of Infrastructure & Facilities',
    companyId: 'comp_2',
    companyName: 'NexGen Health Systems',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    lifecycleStage: 'customer',
    lastActivityAt: '2026-09-29T07:30:00.000Z',
    assignedTo: 'usr_current',
    notes: 'Heading biomedical telemetry modernization initiative across regional centers.',
    createdAt: '2026-08-15T11:00:00.000Z',
  },
  {
    id: 'cont_3',
    name: 'Elena Rostova',
    email: 'elena.rostova@vertexfin.ch',
    phone: '+41 22 789 4512',
    title: 'Head of Digital Transformation',
    companyId: 'comp_3',
    companyName: 'Vertex FinTech Global',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    lifecycleStage: 'mql',
    lastActivityAt: '2026-09-27T14:00:00.000Z',
    assignedTo: 'usr_current',
    notes: 'Leading zero-trust gateway mesh integration for Swiss private cloud.',
    createdAt: '2026-08-20T14:45:00.000Z',
  },
  {
    id: 'cont_4',
    name: 'Lukas Weber',
    email: 'l.weber@solariaenergy.de',
    phone: '+49 30 6543 2118',
    title: 'Chief Technical Officer',
    companyId: 'comp_4',
    companyName: 'Solaria Clean Energy Corp',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    lifecycleStage: 'lead',
    lastActivityAt: '2026-09-28T15:00:00.000Z',
    assignedTo: 'usr_current',
    notes: 'Supervising smart grid telemetry devices across European solar parks.',
    createdAt: '2026-09-01T11:30:00.000Z',
  },
  {
    id: 'cont_5',
    name: 'Priya Sharma',
    email: 'priya.sharma@hyperscalelog.com',
    phone: '+65 6789 0145',
    title: 'Director of Global Operations',
    companyId: 'comp_5',
    companyName: 'HyperScale Logistics & IoT',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    lifecycleStage: 'customer',
    lastActivityAt: '2026-09-26T16:20:00.000Z',
    assignedTo: 'usr_current',
    notes: 'Oversees 300+ connected delivery vehicles in Southeast Asia.',
    createdAt: '2026-09-05T09:15:00.000Z',
  },
];

// 5 Dummy Enquiries / Leads
export const MOCK_LEADS: Lead[] = [
  {
    id: 'lead_1',
    name: 'David Chen',
    company: 'OmniRobotics AI',
    email: 'd.chen@omnirobotics.ai',
    phone: '+1 (555) 432-1098',
    source: 'website',
    status: 'new',
    score: 88,
    assignedTo: 'usr_current',
    estimatedValue: 45000,
    notes: 'Inbound enquiry via website product demo request. Wants autonomous facility telemetry sensors.',
    createdAt: '2026-09-28T10:15:00.000Z',
    updatedAt: '2026-09-28T10:15:00.000Z',
  },
  {
    id: 'lead_2',
    name: 'Amira Al-Mansoor',
    company: 'Gulf Smart Infrastructure',
    email: 'amira@gulfsmart.ae',
    phone: '+971 4 321 9876',
    source: 'linkedin',
    status: 'qualified',
    score: 94,
    assignedTo: 'usr_current',
    estimatedValue: 120000,
    notes: 'Evaluating enterprise IoT deployment across 12 commercial hubs in Dubai and Abu Dhabi.',
    createdAt: '2026-09-25T14:30:00.000Z',
    updatedAt: '2026-09-28T11:00:00.000Z',
  },
  {
    id: 'lead_3',
    name: 'Oliver Wright',
    company: 'EcoGrid Systems UK',
    email: 'o.wright@ecogrid.co.uk',
    phone: '+44 20 7946 0912',
    source: 'referral',
    status: 'discussion',
    score: 82,
    assignedTo: 'usr_current',
    estimatedValue: 68000,
    notes: 'Referred by Solaria Energy. Looking for turnkey installation support and sensor packages.',
    createdAt: '2026-09-22T09:00:00.000Z',
    updatedAt: '2026-09-27T16:00:00.000Z',
  },
  {
    id: 'lead_4',
    name: 'Claire Dubois',
    company: 'Lyon BioTech Innovations',
    email: 'claire.dubois@lyonbiotech.fr',
    phone: '+33 4 72 00 11 22',
    source: 'event',
    status: 'proposal',
    score: 91,
    assignedTo: 'usr_current',
    estimatedValue: 95000,
    notes: 'Met at Paris Tech Summit. Requested detailed quotation for clean-room telemetry nodes.',
    createdAt: '2026-09-18T13:45:00.000Z',
    updatedAt: '2026-09-26T12:00:00.000Z',
  },
  {
    id: 'lead_5',
    name: 'Kenji Takahashi',
    company: 'Nippon Data Center Group',
    email: 'takahashi.k@nippondc.jp',
    phone: '+81 3 5555 0143',
    source: 'cold_outreach',
    status: 'contacted',
    score: 76,
    assignedTo: 'usr_current',
    estimatedValue: 150000,
    notes: 'Introductory presentation delivered. Follow-up review scheduled for next week.',
    createdAt: '2026-09-15T08:00:00.000Z',
    updatedAt: '2026-09-24T09:30:00.000Z',
  },
];

// 5 Dummy Sales Deals (Pipeline)
export const MOCK_DEALS: Deal[] = [
  {
    id: 'deal_1',
    title: 'Enterprise Campus IoT Rollout',
    value: 185000,
    currency: 'USD',
    stage: 'closed_won',
    probability: 100,
    expectedCloseDate: '2026-09-15',
    companyId: 'comp_1',
    companyName: 'AeroSpace Dynamics Ltd',
    contactId: 'cont_1',
    contactName: 'Sarah Jenkins',
    assignedTo: 'usr_current',
    priority: 'high',
    tags: ['Enterprise', 'Hardware + SLA'],
    createdAt: '2026-08-12T10:00:00.000Z',
    updatedAt: '2026-09-15T15:30:00.000Z',
  },
  {
    id: 'deal_2',
    title: 'Hospital Telemetry & Patient Sensor Grid',
    value: 140000,
    currency: 'USD',
    stage: 'negotiation',
    probability: 80,
    expectedCloseDate: '2026-10-15',
    companyId: 'comp_2',
    companyName: 'NexGen Health Systems',
    contactId: 'cont_2',
    contactName: 'Dr. Marcus Vance',
    assignedTo: 'usr_current',
    priority: 'high',
    tags: ['Healthcare', 'Multi-Site'],
    createdAt: '2026-08-18T11:30:00.000Z',
    updatedAt: '2026-09-28T16:00:00.000Z',
  },
  {
    id: 'deal_3',
    title: 'Secure Financial Micro-Gateway Mesh',
    value: 92000,
    currency: 'USD',
    stage: 'proposal_sent',
    probability: 60,
    expectedCloseDate: '2026-11-01',
    companyId: 'comp_3',
    companyName: 'Vertex FinTech Global',
    contactId: 'cont_3',
    contactName: 'Elena Rostova',
    assignedTo: 'usr_current',
    priority: 'medium',
    tags: ['FinTech', 'Compliance'],
    createdAt: '2026-08-25T14:00:00.000Z',
    updatedAt: '2026-09-27T10:00:00.000Z',
  },
  {
    id: 'deal_4',
    title: 'Smart Solar Farm Monitoring Infrastructure',
    value: 64000,
    currency: 'USD',
    stage: 'needs_analysis',
    probability: 40,
    expectedCloseDate: '2026-11-20',
    companyId: 'comp_4',
    companyName: 'Solaria Clean Energy Corp',
    contactId: 'cont_4',
    contactName: 'Lukas Weber',
    assignedTo: 'usr_current',
    priority: 'medium',
    tags: ['Green Energy', 'Field Work'],
    createdAt: '2026-09-03T09:30:00.000Z',
    updatedAt: '2026-09-28T14:00:00.000Z',
  },
  {
    id: 'deal_5',
    title: 'Distribution Hub Fleet Telematics Upgrade',
    value: 210000,
    currency: 'USD',
    stage: 'qualification',
    probability: 30,
    expectedCloseDate: '2026-12-10',
    companyId: 'comp_5',
    companyName: 'HyperScale Logistics & IoT',
    contactId: 'cont_5',
    contactName: 'Priya Sharma',
    assignedTo: 'usr_current',
    priority: 'high',
    tags: ['Logistics', 'Fleet GPS'],
    createdAt: '2026-09-08T10:15:00.000Z',
    updatedAt: '2026-09-26T11:00:00.000Z',
  },
];

// 5 Dummy Quotations
export const MOCK_QUOTATIONS: Quotation[] = [
  {
    id: 'quot_1',
    quoteNumber: 'Q-2026-001',
    title: 'Enterprise IoT Hub & Gateways Deployment',
    dealId: 'deal_1',
    dealTitle: 'Enterprise Campus IoT Rollout',
    contactName: 'Sarah Jenkins',
    contactEmail: 'sarah.jenkins@aerospacedynamics.io',
    companyName: 'AeroSpace Dynamics Ltd',
    status: 'accepted',
    issueDate: '2026-09-10',
    validUntil: '2026-10-10',
    lineItems: [
      { id: 'li_1', description: 'Smart IoT Central Gateways (Industrial Pro)', quantity: 40, unitPrice: 1500, discount: 5, amount: 57000 },
      { id: 'li_2', description: 'Edge Computing Micro-Relay Nodes', quantity: 20, unitPrice: 3000, discount: 0, amount: 60000 },
      { id: 'li_3', description: 'Full Onsite Installation, Cabling & Setup SLA', quantity: 1, unitPrice: 51000, discount: 0, amount: 51000 },
    ],
    subtotal: 168000,
    taxRate: 10,
    taxAmount: 16800,
    total: 184800,
    notes: 'Deliveries to Main Plant Building 4. Net 30 payment terms.',
    terms: 'Standard 24-month hardware warranty and on-site SLA included.',
    createdBy: 'Admin',
    createdAt: '2026-09-10T10:00:00.000Z',
  },
  {
    id: 'quot_2',
    quoteNumber: 'Q-2026-002',
    title: 'BioTelemetry Diagnostic Gateway Package',
    dealId: 'deal_2',
    dealTitle: 'Hospital Telemetry & Patient Sensor Grid',
    contactName: 'Dr. Marcus Vance',
    contactEmail: 'm.vance@nexgenhealth.com',
    companyName: 'NexGen Health Systems',
    status: 'sent',
    issueDate: '2026-09-22',
    validUntil: '2026-10-22',
    lineItems: [
      { id: 'li_4', description: 'Medical Grade Wireless Telemetry Transceivers', quantity: 80, unitPrice: 900, discount: 5, amount: 68400 },
      { id: 'li_5', description: 'Encrypted Hospital Signal Repeater Hubs', quantity: 30, unitPrice: 800, discount: 0, amount: 24000 },
      { id: 'li_6', description: '24/7 Redundant Telemetry Cloud Monitoring (Annual)', quantity: 1, unitPrice: 34872, discount: 0, amount: 34872 },
    ],
    subtotal: 127272,
    taxRate: 10,
    taxAmount: 12728,
    total: 140000,
    notes: 'Medical device ISO-13485 compliance certification included.',
    terms: '50% advance upon contract signing, 50% upon completed site commissioning.',
    createdBy: 'Admin',
    createdAt: '2026-09-22T14:30:00.000Z',
  },
  {
    id: 'quot_3',
    quoteNumber: 'Q-2026-003',
    title: 'FinTech Zero-Trust Sensor Array',
    dealId: 'deal_3',
    dealTitle: 'Secure Financial Micro-Gateway Mesh',
    contactName: 'Elena Rostova',
    contactEmail: 'elena.rostova@vertexfin.ch',
    companyName: 'Vertex FinTech Global',
    status: 'sent',
    issueDate: '2026-09-25',
    validUntil: '2026-10-25',
    lineItems: [
      { id: 'li_7', description: 'Tamper-Evident Sensor Nodes', quantity: 50, unitPrice: 750, discount: 0, amount: 37500 },
      { id: 'li_8', description: 'Hardware Cryptographic Data Firewall Bridges', quantity: 10, unitPrice: 2500, discount: 0, amount: 25000 },
      { id: 'li_9', description: 'SOC-2 Compliance Security Audit Pack', quantity: 1, unitPrice: 21136, discount: 0, amount: 21136 },
    ],
    subtotal: 83636,
    taxRate: 10,
    taxAmount: 8364,
    total: 92000,
    notes: 'Subject to FINMA compliance check and security review.',
    terms: 'Net 45 payment terms upon hardware delivery.',
    createdBy: 'Admin',
    createdAt: '2026-09-25T11:15:00.000Z',
  },
  {
    id: 'quot_4',
    quoteNumber: 'Q-2026-004',
    title: 'Photovoltaic Array Telematics Suite',
    dealId: 'deal_4',
    dealTitle: 'Smart Solar Farm Monitoring Infrastructure',
    contactName: 'Lukas Weber',
    contactEmail: 'l.weber@solariaenergy.de',
    companyName: 'Solaria Clean Energy Corp',
    status: 'draft',
    issueDate: '2026-09-28',
    validUntil: '2026-10-28',
    lineItems: [
      { id: 'li_10', description: 'Weatherproof Inverter Transponder Modules', quantity: 25, unitPrice: 1200, discount: 0, amount: 30000 },
      { id: 'li_11', description: 'Solar Irradiance Weather Monitoring Stations', quantity: 5, unitPrice: 2500, discount: 0, amount: 12500 },
      { id: 'li_12', description: 'Onsite Installation & Radio Signal Calibration', quantity: 1, unitPrice: 15681, discount: 0, amount: 15681 },
    ],
    subtotal: 58181,
    taxRate: 10,
    taxAmount: 5819,
    total: 64000,
    notes: 'Includes IP67 outdoor ruggedized junction enclosures.',
    terms: '12-month standard maintenance warranty included.',
    createdBy: 'Admin',
    createdAt: '2026-09-28T09:00:00.000Z',
  },
  {
    id: 'quot_5',
    quoteNumber: 'Q-2026-005',
    title: 'Fleet GPS Tracking & Vehicle Diagnostic Units',
    dealId: 'deal_5',
    dealTitle: 'Distribution Hub Fleet Telematics Upgrade',
    contactName: 'Priya Sharma',
    contactEmail: 'priya.sharma@hyperscalelog.com',
    companyName: 'HyperScale Logistics & IoT',
    status: 'draft',
    issueDate: '2026-09-28',
    validUntil: '2026-10-31',
    lineItems: [
      { id: 'li_13', description: 'Heavy-Duty OBD-II Fleet GPS Transceivers', quantity: 300, unitPrice: 350, discount: 5, amount: 99750 },
      { id: 'li_14', description: 'Central Hub Dispatcher Touchscreen Terminals', quantity: 10, unitPrice: 3500, discount: 0, amount: 35000 },
      { id: 'li_15', description: 'Fleet Telematics Cloud API Enterprise License (1 Yr)', quantity: 1, unitPrice: 56159, discount: 0, amount: 56159 },
    ],
    subtotal: 190909,
    taxRate: 10,
    taxAmount: 19091,
    total: 210000,
    notes: 'Installation in batches of 50 vehicles over weekend shifts.',
    terms: 'Yearly subscription renewal for cloud API after 12 months.',
    createdBy: 'Admin',
    createdAt: '2026-09-28T16:00:00.000Z',
  },
];

// 5 Dummy Operations: Installations (Includes today's date for live dashboard metrics)
export const MOCK_INSTALLATIONS: Installation[] = [
  {
    id: 'inst_1',
    customerId: 'cont_1',
    customerName: 'Sarah Jenkins',
    dealId: 'deal_1',
    dealTitle: 'Enterprise Campus IoT Rollout',
    bookingDate: '2026-09-20',
    installationDate: '2026-09-29', // Today!
    installer: 'Alex Rivera',
    status: 'completed',
    siteAddress: 'Building 4, 100 Industrial Parkway, Seattle, WA',
    contactPhone: '+1 (555) 234-8910',
    notes: 'Central gateway mounted and calibrated. Signal test verified at 99.8%. All 40 gateways active.',
    createdAt: '2026-09-20T10:00:00.000Z',
    updatedAt: '2026-09-29T11:30:00.000Z',
  },
  {
    id: 'inst_2',
    customerId: 'cont_2',
    customerName: 'Dr. Marcus Vance',
    dealId: 'deal_2',
    dealTitle: 'Hospital Telemetry & Patient Sensor Grid',
    bookingDate: '2026-09-25',
    installationDate: '2026-09-29', // Today!
    installer: 'Michael Chen',
    status: 'in_progress',
    siteAddress: 'Wing C, 450 Health Sciences Blvd, Boston, MA',
    contactPhone: '+1 (555) 876-5444',
    notes: 'Installation crew currently routing cables through secondary riser in Cardiology ward.',
    createdAt: '2026-09-25T14:00:00.000Z',
    updatedAt: '2026-09-29T13:00:00.000Z',
  },
  {
    id: 'inst_3',
    customerId: 'cont_3',
    customerName: 'Elena Rostova',
    dealId: 'deal_3',
    dealTitle: 'Secure Financial Micro-Gateway Mesh',
    bookingDate: '2026-09-27',
    installationDate: '2026-10-02',
    installer: 'Liam O\'Connor',
    status: 'scheduled',
    siteAddress: 'Rue du Rhône 42, 1204 Genève, Switzerland',
    contactPhone: '+41 22 789 4512',
    notes: 'Security clearance verified. Pre-installation hardware bench test passed with zero errors.',
    createdAt: '2026-09-27T09:30:00.000Z',
    updatedAt: '2026-09-27T09:30:00.000Z',
  },
  {
    id: 'inst_4',
    customerId: 'cont_4',
    customerName: 'Lukas Weber',
    dealId: 'deal_4',
    dealTitle: 'Smart Solar Farm Monitoring Infrastructure',
    bookingDate: '2026-09-28',
    installationDate: '2026-10-05',
    installer: 'Alex Rivera',
    status: 'pending',
    siteAddress: 'Solarfeld Ost 12, 14532 Kleinmachnow, Germany',
    contactPhone: '+49 30 6543 2118',
    notes: 'Awaiting delivery of specialized weatherproof brackets and cellular antennas.',
    createdAt: '2026-09-28T11:00:00.000Z',
    updatedAt: '2026-09-28T11:00:00.000Z',
  },
  {
    id: 'inst_5',
    customerId: 'cont_5',
    customerName: 'Priya Sharma',
    dealId: 'deal_5',
    dealTitle: 'Distribution Hub Fleet Telematics Upgrade',
    bookingDate: '2026-09-26',
    installationDate: '2026-10-08',
    installer: 'Daniel Wong',
    status: 'scheduled',
    siteAddress: '15 Pioneer Sector 1, Jurong, Singapore',
    contactPhone: '+65 6789 0145',
    notes: 'Batch #1 of 50 prime movers scheduled for weekend depot installation.',
    createdAt: '2026-09-26T15:20:00.000Z',
    updatedAt: '2026-09-26T15:20:00.000Z',
  },
];

// 5 Dummy Operations: Installer Schedule Slots
export const MOCK_INSTALLER_SCHEDULES: InstallerScheduleItem[] = [
  {
    id: 'sch_1',
    installer: 'Alex Rivera',
    siteVisitTime: '08:30 AM - 11:30 AM',
    visitDate: '2026-09-29', // Today!
    customerId: 'cont_1',
    customerName: 'Sarah Jenkins (AeroSpace Dynamics)',
    installationId: 'inst_1',
    status: 'completed',
    siteAddress: 'Building 4, 100 Industrial Parkway, Seattle, WA',
    notes: 'Gateway commissioning completed and handover document signed by facilities manager.',
    createdAt: '2026-09-20T10:30:00.000Z',
    updatedAt: '2026-09-29T11:30:00.000Z',
  },
  {
    id: 'sch_2',
    installer: 'Michael Chen',
    siteVisitTime: '01:00 PM - 04:30 PM',
    visitDate: '2026-09-29', // Today!
    customerId: 'cont_2',
    customerName: 'Dr. Marcus Vance (NexGen Health)',
    installationId: 'inst_2',
    status: 'in_progress',
    siteAddress: 'Wing C, 450 Health Sciences Blvd, Boston, MA',
    notes: 'Currently on-site running RF spectrum verification and transceiver placements.',
    createdAt: '2026-09-25T14:30:00.000Z',
    updatedAt: '2026-09-29T13:00:00.000Z',
  },
  {
    id: 'sch_3',
    installer: 'Liam O\'Connor',
    siteVisitTime: '09:00 AM - 12:00 PM',
    visitDate: '2026-10-02',
    customerId: 'cont_3',
    customerName: 'Elena Rostova (Vertex FinTech)',
    installationId: 'inst_3',
    status: 'confirmed',
    siteAddress: 'Rue du Rhône 42, 1204 Genève, Switzerland',
    notes: 'Escort and biometric badge registration ready at reception.',
    createdAt: '2026-09-27T10:00:00.000Z',
    updatedAt: '2026-09-27T10:00:00.000Z',
  },
  {
    id: 'sch_4',
    installer: 'Alex Rivera',
    siteVisitTime: '10:00 AM - 01:30 PM',
    visitDate: '2026-10-05',
    customerId: 'cont_4',
    customerName: 'Lukas Weber (Solaria Clean Energy)',
    installationId: 'inst_4',
    status: 'confirmed',
    siteAddress: 'Solarfeld Ost 12, 14532 Kleinmachnow, Germany',
    notes: 'Weather check confirms clear conditions for outdoor inverter mounting.',
    createdAt: '2026-09-28T11:30:00.000Z',
    updatedAt: '2026-09-28T11:30:00.000Z',
  },
  {
    id: 'sch_5',
    installer: 'Daniel Wong',
    siteVisitTime: '08:00 AM - 05:00 PM',
    visitDate: '2026-10-08',
    customerId: 'cont_5',
    customerName: 'Priya Sharma (HyperScale Logistics)',
    installationId: 'inst_5',
    status: 'confirmed',
    siteAddress: '15 Pioneer Sector 1, Jurong, Singapore',
    notes: 'Full-day scheduled slot to complete vehicle batch installation.',
    createdAt: '2026-09-26T16:00:00.000Z',
    updatedAt: '2026-09-26T16:00:00.000Z',
  },
];

// 5 Dummy Operations: Device Inventory
export const MOCK_DEVICE_INVENTORY: DeviceInventoryItem[] = [
  {
    id: 'dev_1',
    deviceName: 'Smart Industrial IoT Gateway (Pro)',
    category: 'IoT Gateways',
    sku: 'GW-PRO-900',
    requiredQty: 60,
    availableQty: 45,
    allocatedQty: 35,
    unit: 'units',
    updatedAt: '2026-09-29',
  },
  {
    id: 'dev_2',
    deviceName: 'Wireless Medical Telemetry Node',
    category: 'Medical Sensors',
    sku: 'MED-TEL-420',
    requiredQty: 120,
    availableQty: 80,
    allocatedQty: 65,
    unit: 'units',
    updatedAt: '2026-09-29',
  },
  {
    id: 'dev_3',
    deviceName: 'Encrypted Financial Hardware Bridge',
    category: 'Security Appliances',
    sku: 'SEC-BRG-10X',
    requiredQty: 25,
    availableQty: 30,
    allocatedQty: 15,
    unit: 'units',
    updatedAt: '2026-09-28',
  },
  {
    id: 'dev_4',
    deviceName: 'Weatherproof Solar Array Transponder',
    category: 'Environmental Sensors',
    sku: 'SOL-ENV-880',
    requiredQty: 50,
    availableQty: 70,
    allocatedQty: 25,
    unit: 'units',
    updatedAt: '2026-09-28',
  },
  {
    id: 'dev_5',
    deviceName: 'Heavy Duty OBD-II Fleet GPS Transceiver',
    category: 'Fleet Telematics',
    sku: 'FLT-GPS-300',
    requiredQty: 350,
    availableQty: 210,
    allocatedQty: 180,
    unit: 'units',
    updatedAt: '2026-09-27',
  },
];

// 5 Dummy Tasks & Follow-up Reminders
export const MOCK_TASKS: Task[] = [
  {
    id: 'task_1',
    title: 'Review Final Signed Contract with AeroSpace',
    description: 'Verify sign-off and confirm dispatch schedule for production campus gateway installation.',
    type: 'quote_review',
    priority: 'urgent',
    status: 'pending',
    dueDate: '2026-09-29', // Today!
    dueTime: '11:00 AM',
    assignedTo: 'usr_current',
    relatedToType: 'company',
    relatedToId: 'comp_1',
    relatedToName: 'AeroSpace Dynamics Ltd',
    createdAt: '2026-09-28T09:00:00.000Z',
  },
  {
    id: 'task_2',
    title: 'Clinical Validation Walkthrough Call',
    description: 'Review hospital telemetry installation progress with engineering and cardiology leads.',
    type: 'call',
    priority: 'high',
    status: 'pending',
    dueDate: '2026-09-29', // Today!
    dueTime: '02:30 PM',
    assignedTo: 'usr_current',
    relatedToType: 'contact',
    relatedToId: 'cont_2',
    relatedToName: 'Dr. Marcus Vance',
    createdAt: '2026-09-28T14:00:00.000Z',
  },
  {
    id: 'task_3',
    title: 'Executive Demo: OmniRobotics AI Facility Architecture',
    description: 'Present architecture diagram and live sensor dashboard to technical steering committee.',
    type: 'demo',
    priority: 'medium',
    status: 'pending',
    dueDate: '2026-09-30',
    dueTime: '10:00 AM',
    assignedTo: 'usr_current',
    relatedToType: 'lead',
    relatedToId: 'lead_1',
    relatedToName: 'David Chen (OmniRobotics)',
    createdAt: '2026-09-28T11:00:00.000Z',
  },
  {
    id: 'task_4',
    title: 'Follow-up on Proposal Q-2026-003',
    description: 'Send security compliance whitepaper and check for legal sign-off on gateway mesh.',
    type: 'email',
    priority: 'high',
    status: 'pending',
    dueDate: '2026-10-01',
    dueTime: '09:30 AM',
    assignedTo: 'usr_current',
    relatedToType: 'deal',
    relatedToId: 'deal_3',
    relatedToName: 'Secure Financial Micro-Gateway Mesh',
    createdAt: '2026-09-27T15:00:00.000Z',
  },
  {
    id: 'task_5',
    title: 'Quarterly Review & Solar Inverter Maintenance Sync',
    description: 'Finalized specification sheet for weatherproof transponder rollout.',
    type: 'meeting',
    priority: 'low',
    status: 'completed',
    dueDate: '2026-09-28',
    dueTime: '03:00 PM',
    assignedTo: 'usr_current',
    relatedToType: 'contact',
    relatedToId: 'cont_4',
    relatedToName: 'Lukas Weber',
    completedAt: '2026-09-28T16:00:00.000Z',
    createdAt: '2026-09-25T11:00:00.000Z',
  },
];

// 5 Dummy Activities (Timeline Feed)
export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: 'act_1',
    type: 'deal_stage_changed',
    title: 'Deal "Enterprise Campus IoT Rollout" moved to CLOSED WON',
    description: 'Probability set to 100%. Total closed contract value: $185,000.',
    performedBy: 'Admin',
    performedById: 'usr_current',
    timestamp: '2026-09-29T08:15:00.000Z',
    relatedToType: 'deal',
    relatedToId: 'deal_1',
    relatedToName: 'Enterprise Campus IoT Rollout',
  },
  {
    id: 'act_2',
    type: 'quotation_created',
    title: 'Quotation Q-2026-002 created & dispatched',
    description: 'For NexGen Health Systems (Dr. Marcus Vance) amounting to $140,000.',
    performedBy: 'Admin',
    performedById: 'usr_current',
    timestamp: '2026-09-28T16:30:00.000Z',
    relatedToType: 'deal',
    relatedToId: 'deal_2',
    relatedToName: 'Hospital Telemetry & Patient Sensor Grid',
  },
  {
    id: 'act_3',
    type: 'call',
    title: 'Discovery Call with Amira Al-Mansoor',
    description: 'Discussed 12-site commercial rollout. Client requested customized SLA proposal.',
    performedBy: 'Admin',
    performedById: 'usr_current',
    timestamp: '2026-09-28T11:00:00.000Z',
    durationMinutes: 35,
    outcome: 'Qualified lead and scheduled technical deep-dive.',
    relatedToType: 'lead',
    relatedToId: 'lead_2',
    relatedToName: 'Amira Al-Mansoor',
  },
  {
    id: 'act_4',
    type: 'meeting',
    title: 'Geneva Data Center Architectural Review',
    description: 'Reviewed zero-trust firewall compliance and server rack physical constraints.',
    performedBy: 'Admin',
    performedById: 'usr_current',
    timestamp: '2026-09-27T14:00:00.000Z',
    durationMinutes: 60,
    outcome: 'Approved hardware specifications and site security clearance.',
    relatedToType: 'deal',
    relatedToId: 'deal_3',
    relatedToName: 'Vertex FinTech Global',
  },
  {
    id: 'act_5',
    type: 'note',
    title: 'Technical Note: Photovoltaic Telemetry Specs',
    description: 'Lukas confirmed requirement for IP67 weatherproof casing and cellular failover.',
    performedBy: 'Admin',
    performedById: 'usr_current',
    timestamp: '2026-09-26T09:45:00.000Z',
    relatedToType: 'contact',
    relatedToId: 'cont_4',
    relatedToName: 'Lukas Weber',
  },
];
